-- Add transcript text columns to bookings table
-- Raw transcript is cached from Whereby on first fetch (avoids repeated API calls)
-- Cleaned transcript is generated by OpenAI after summary is created

ALTER TABLE bookings ADD COLUMN IF NOT EXISTS transcript_text TEXT;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS cleaned_transcript TEXT;
