-- ============================================================================
-- Let the app read (sign) the vocab word pronunciation clips directly.
--
-- The clips are generated by scripts/gen-vocab-word-audio.mjs into the PRIVATE
-- `test-assets` bucket under the `vocab-audio/` prefix. This policy grants
-- authenticated users SELECT on just that prefix, so the app can call
-- supabase.storage.from('test-assets').createSignedUrl(...) client-side without
-- a backend round-trip. Nothing else in test-assets is exposed (test content,
-- recordings, etc. stay locked to the service role).
--
-- Word pronunciations are not sensitive; this only makes them signable by a
-- logged-in user, not public. Idempotent.
-- ============================================================================

DROP POLICY IF EXISTS "vocab word audio readable" ON storage.objects;

CREATE POLICY "vocab word audio readable"
  ON storage.objects FOR SELECT
  TO authenticated
  USING ( bucket_id = 'test-assets' AND name LIKE 'vocab-audio/%' );
