-- Vocab 102 - unit REVIEW capstones (standalone; only -review lessons).

-- Unit 1 review: A reunion
INSERT INTO vocab_lessons (slug, level_index, order_index, theme_id, title_en, title_ja, published, free) VALUES
  ('vocab-102-u1-review', 1, 90, (SELECT id FROM vocab_categories WHERE slug='personality-traits'), 'Review', '復習', TRUE, TRUE)
ON CONFLICT (slug) DO UPDATE SET level_index=EXCLUDED.level_index, order_index=EXCLUDED.order_index, theme_id=EXCLUDED.theme_id, title_en=EXCLUDED.title_en, title_ja=EXCLUDED.title_ja, published=EXCLUDED.published, free=EXCLUDED.free;
DELETE FROM vocab_lesson_items WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u1-review');
INSERT INTO vocab_lesson_items (lesson_id, sense_id, order_index)
SELECT (SELECT id FROM vocab_lessons WHERE slug='vocab-102-u1-review'), s.id, x.ord FROM (VALUES
  ('confident.adj.sure',0),('shy.adj.timid',1),('honest.adj.truthful',2),('lazy.adj.idle',3),('generous.adj.giving',4),('patient.adj.calm',5),('selfish.adj.egotist',6),('reliable.adj.dependable',7),('get-along.phrv.relate',8),('fall-out.phrv.quarrel',9),('make-up.phrv.reconcile',10),('look-up-to.phrv.admire',11),('put-up-with.phrv.tolerate',12),('hang-out.phrv.socialize',13),('tell-off.phrv.scold',14),('split-up.phrv.separate',15),('grow-up.phrv.mature',16),('childhood.n.youth',17),('hometown.n.origin',18),('generation.n.cohort',19),('retire.v.stopwork',20),('ambition.n.goal',21),('achieve.v.succeed',22),('elderly.adj.old',23)
) AS x(slug, ord) JOIN vocab_senses s ON s.slug = x.slug ON CONFLICT DO NOTHING;
DELETE FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u1-review');
INSERT INTO vocab_scenes (lesson_id, goal, order_index, title_en, title_ja, setting, npc_role) VALUES
  ((SELECT id FROM vocab_lessons WHERE slug='vocab-102-u1-review'), 'conversation', 0, 'A reunion', '同窓会', 'cafe', 'old friend');
INSERT INTO vocab_scene_lines (scene_id, order_index, speaker, text_en, text_ja, blank_answer, blank_sense_id, options) VALUES
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u1-review') AND goal='conversation'), 0, 'npc', 'It''s been years! You look great.', '久しぶり！元気そうだね。', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u1-review') AND goal='conversation'), 1, 'user', 'Thanks! I''m more {confident} now than in school.', 'ありがとう！学生の頃より自信がついた。', 'confident', (SELECT id FROM vocab_senses WHERE slug='confident.adj.sure'), ARRAY['confident','shy','lazy','generous']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u1-review') AND goal='conversation'), 2, 'npc', 'You always had it in you. Remember our class?', 'もともと素質あったよ。あのクラス覚えてる？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u1-review') AND goal='conversation'), 3, 'user', 'Of course. We all had to {grow up} fast after graduation.', 'もちろん。卒業後、みんな早く大人にならなきゃだった。', 'grow up', (SELECT id FROM vocab_senses WHERE slug='grow-up.phrv.mature'), ARRAY['grow up','retire','hang out','achieve']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u1-review') AND goal='conversation'), 4, 'npc', 'So true. Have you seen Mei?', '本当に。メイには会った？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u1-review') AND goal='conversation'), 5, 'user', 'Not lately. She always had huge {ambition}, though.', '最近は会ってない。でも昔から大きな野心があった。', 'ambition', (SELECT id FROM vocab_senses WHERE slug='ambition.n.goal'), ARRAY['ambition','childhood','hometown','generation']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u1-review') AND goal='conversation'), 6, 'npc', 'She runs a startup now. And Ken?', '今はスタートアップを経営してる。ケンは？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u1-review') AND goal='conversation'), 7, 'user', 'Ken''s still so {generous}; he paid for all our coffees today.', 'ケンは相変わらず気前がいい。今日みんなのコーヒーをおごってくれた。', 'generous', (SELECT id FROM vocab_senses WHERE slug='generous.adj.giving'), ARRAY['generous','selfish','shy','lazy']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u1-review') AND goal='conversation'), 8, 'npc', 'Ha, classic Ken. He set up this reunion, you know.', 'はは、ケンらしい。この同窓会も彼が仕切ったんだよ。', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u1-review') AND goal='conversation'), 9, 'user', 'Really {reliable} as ever; he never drops a plan.', '相変わらず頼りになる。約束を絶対すっぽかさない。', 'reliable', (SELECT id FROM vocab_senses WHERE slug='reliable.adj.dependable'), ARRAY['reliable','shy','lazy','selfish']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u1-review') AND goal='conversation'), 10, 'npc', 'We''re lucky to have him. Do you still see the group?', '彼がいて助かる。みんなとはまだ会う？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u1-review') AND goal='conversation'), 11, 'user', 'I want to. Do you all still {hang out} often?', '会いたい。みんな今もよくつるんでる？', 'hang out', (SELECT id FROM vocab_senses WHERE slug='hang-out.phrv.socialize'), ARRAY['hang out','tell off','fall out','split up']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u1-review') AND goal='conversation'), 12, 'npc', 'Every month! You should come.', '毎月ね！来なよ。', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u1-review') AND goal='conversation'), 13, 'user', 'I''d love that. Honestly, I still {look up to} you all.', 'ぜひ。正直、今もみんなを尊敬してる。', 'look up to', (SELECT id FROM vocab_senses WHERE slug='look-up-to.phrv.admire'), ARRAY['look up to','put up with','tell off','split up']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u1-review') AND goal='conversation'), 14, 'npc', 'Aw. Then it''s settled, {{user_name}}, see you next month!', 'うれしい。じゃあ決まり、{{user_name}}、来月ね！', NULL, NULL, NULL);

-- Unit 2 review: After a hard week
INSERT INTO vocab_lessons (slug, level_index, order_index, theme_id, title_en, title_ja, published, free) VALUES
  ('vocab-102-u2-review', 2, 90, (SELECT id FROM vocab_categories WHERE slug='emotions'), 'Review', '復習', TRUE, TRUE)
ON CONFLICT (slug) DO UPDATE SET level_index=EXCLUDED.level_index, order_index=EXCLUDED.order_index, theme_id=EXCLUDED.theme_id, title_en=EXCLUDED.title_en, title_ja=EXCLUDED.title_ja, published=EXCLUDED.published, free=EXCLUDED.free;
DELETE FROM vocab_lesson_items WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u2-review');
INSERT INTO vocab_lesson_items (lesson_id, sense_id, order_index)
SELECT (SELECT id FROM vocab_lessons WHERE slug='vocab-102-u2-review'), s.id, x.ord FROM (VALUES
  ('nervous.adj.tense',0),('relieved.adj.eased',1),('embarrassed.adj.ashamed',2),('jealous.adj.envious',3),('proud.adj.pleased',4),('frustrated.adj.annoyed',5),('anxious.adj.worried',6),('grateful.adj.thankful',7),('opinion.n.view',8),('agree.v.concur',9),('disagree.v.differ',10),('suggest.v.propose',11),('prefer.v.rather',12),('admit.v.confess',13),('doubt.v.question',14),('reckon.v.think',15),('cheer-up.phrv.gladden',16),('calm-down.phrv.settle',17),('get-over.phrv.recover',18),('look-forward-to.phrv.anticipate',19),('freak-out.phrv.panic',20),('chill-out.phrv.relax',21),('fed-up.phr.annoyed',22),('feel-like.phrv.want',23)
) AS x(slug, ord) JOIN vocab_senses s ON s.slug = x.slug ON CONFLICT DO NOTHING;
DELETE FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u2-review');
INSERT INTO vocab_scenes (lesson_id, goal, order_index, title_en, title_ja, setting, npc_role) VALUES
  ((SELECT id FROM vocab_lessons WHERE slug='vocab-102-u2-review'), 'conversation', 0, 'After a hard week', '大変な一週間のあと', 'cafe', 'friend');
INSERT INTO vocab_scene_lines (scene_id, order_index, speaker, text_en, text_ja, blank_answer, blank_sense_id, options) VALUES
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u2-review') AND goal='conversation'), 0, 'npc', 'You look brighter than last week!', '先週より元気そうだね！', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u2-review') AND goal='conversation'), 1, 'user', 'I feel {relieved}; my exams are finally done.', 'ほっとしてる。やっと試験が終わった。', 'relieved', (SELECT id FROM vocab_senses WHERE slug='relieved.adj.eased'), ARRAY['relieved','nervous','jealous','proud']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u2-review') AND goal='conversation'), 2, 'npc', 'Congrats! Were they hard?', 'おめでとう！難しかった？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u2-review') AND goal='conversation'), 3, 'user', 'So hard. I was {nervous} the whole week.', 'すごく。一週間ずっと緊張してた。', 'nervous', (SELECT id FROM vocab_senses WHERE slug='nervous.adj.tense'), ARRAY['nervous','proud','grateful','relieved']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u2-review') AND goal='conversation'), 4, 'npc', 'But you got through it.', 'でも乗り切ったね。', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u2-review') AND goal='conversation'), 5, 'user', 'I did. I''m actually {proud} of my results.', 'うん。実は結果を誇りに思ってる。', 'proud', (SELECT id FROM vocab_senses WHERE slug='proud.adj.pleased'), ARRAY['proud','embarrassed','jealous','frustrated']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u2-review') AND goal='conversation'), 6, 'npc', 'You should be! Celebrate this weekend?', '当然だよ！週末お祝いする？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u2-review') AND goal='conversation'), 7, 'user', 'Yes! I really {look forward to} some rest.', 'うん！休むのを本当に楽しみにしてる。', 'look forward to', (SELECT id FROM vocab_senses WHERE slug='look-forward-to.phrv.anticipate'), ARRAY['look forward to','get over','freak out','fed up']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u2-review') AND goal='conversation'), 8, 'npc', 'Let''s plan something calm.', 'ゆったりした計画にしよう。', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u2-review') AND goal='conversation'), 9, 'user', 'Perfect. I need to {calm down} after all that stress.', 'いいね。あのストレスのあと、落ち着きたい。', 'calm down', (SELECT id FROM vocab_senses WHERE slug='calm-down.phrv.settle'), ARRAY['calm down','freak out','cheer up','chill out']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u2-review') AND goal='conversation'), 10, 'npc', 'How about a picnic? Or a movie?', 'ピクニックは？それとも映画？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u2-review') AND goal='conversation'), 11, 'user', 'In my {opinion}, a picnic sounds lovely.', '私の意見では、ピクニックが素敵。', 'opinion', (SELECT id FROM vocab_senses WHERE slug='opinion.n.view'), ARRAY['opinion','doubt','agree','suggest']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u2-review') AND goal='conversation'), 12, 'npc', 'Then a picnic it is.', 'じゃあピクニックで決まり。', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u2-review') AND goal='conversation'), 13, 'user', 'I {agree}, that''s settled!', '賛成、決まりね！', 'agree', (SELECT id FROM vocab_senses WHERE slug='agree.v.concur'), ARRAY['agree','disagree','admit','doubt']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u2-review') AND goal='conversation'), 14, 'npc', 'Can''t wait, {{user_name}}!', '楽しみ、{{user_name}}！', NULL, NULL, NULL);

-- Unit 3 review: Starting a new job
INSERT INTO vocab_lessons (slug, level_index, order_index, theme_id, title_en, title_ja, published, free) VALUES
  ('vocab-102-u3-review', 3, 90, (SELECT id FROM vocab_categories WHERE slug='workplace'), 'Review', '復習', TRUE, TRUE)
ON CONFLICT (slug) DO UPDATE SET level_index=EXCLUDED.level_index, order_index=EXCLUDED.order_index, theme_id=EXCLUDED.theme_id, title_en=EXCLUDED.title_en, title_ja=EXCLUDED.title_ja, published=EXCLUDED.published, free=EXCLUDED.free;
DELETE FROM vocab_lesson_items WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u3-review');
INSERT INTO vocab_lesson_items (lesson_id, sense_id, order_index)
SELECT (SELECT id FROM vocab_lessons WHERE slug='vocab-102-u3-review'), s.id, x.ord FROM (VALUES
  ('salary.n.pay',0),('promotion.n.advance',1),('overtime.n.extrahours',2),('staff.n.employees',3),('manager.n.boss',4),('department.n.section',5),('shift.n.workperiod',6),('contract.n.agreement',7),('apply-for.phrv.request',8),('take-on.phrv.accept',9),('hand-in.phrv.submit',10),('fill-in.phrv.complete',11),('turn-down.phrv.refuse',12),('carry-out.phrv.perform',13),('look-into.phrv.investigate',14),('sort-out.phrv.resolve',15),('schedule.n.timetable',16),('arrange.v.organize',17),('cancel.v.calloff',18),('postpone.v.delay',19),('attend.v.gotomeeting',20),('agenda.n.itemlist',21),('presentation.n.talk',22),('workload.n.amount',23)
) AS x(slug, ord) JOIN vocab_senses s ON s.slug = x.slug ON CONFLICT DO NOTHING;
DELETE FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u3-review');
INSERT INTO vocab_scenes (lesson_id, goal, order_index, title_en, title_ja, setting, npc_role) VALUES
  ((SELECT id FROM vocab_lessons WHERE slug='vocab-102-u3-review'), 'conversation', 0, 'Starting a new job', '新しい仕事の始まり', 'cafe', 'friend');
INSERT INTO vocab_scene_lines (scene_id, order_index, speaker, text_en, text_ja, blank_answer, blank_sense_id, options) VALUES
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u3-review') AND goal='conversation'), 0, 'npc', 'You start your new job Monday, right?', '月曜から新しい仕事だよね？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u3-review') AND goal='conversation'), 1, 'user', 'Yes! So glad I decided to {apply for} it.', 'うん！応募して本当によかった。', 'apply for', (SELECT id FROM vocab_senses WHERE slug='apply-for.phrv.request'), ARRAY['apply for','hand in','turn down','sort out']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u3-review') AND goal='conversation'), 2, 'npc', 'Do you know your manager yet?', '上司はもう分かった？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u3-review') AND goal='conversation'), 3, 'user', 'Yeah, my {manager} seems really kind.', 'うん、上司はすごく優しそう。', 'manager', (SELECT id FROM vocab_senses WHERE slug='manager.n.boss'), ARRAY['manager','salary','staff','shift']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u3-review') AND goal='conversation'), 4, 'npc', 'Nice. Good pay?', 'いいね。給料は？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u3-review') AND goal='conversation'), 5, 'user', 'The {salary} is a solid step up.', '給料はしっかり上がった。', 'salary', (SELECT id FROM vocab_senses WHERE slug='salary.n.pay'), ARRAY['salary','agenda','shift','contract']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u3-review') AND goal='conversation'), 6, 'npc', 'Any events your first week?', '初週に予定は？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u3-review') AND goal='conversation'), 7, 'user', 'I {attend} a team meeting on day one.', '初日にチーム会議に出席する。', 'attend', (SELECT id FROM vocab_senses WHERE slug='attend.v.gotomeeting'), ARRAY['attend','cancel','arrange','postpone']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u3-review') AND goal='conversation'), 8, 'npc', 'Do you know what it''s about?', '内容は分かる？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u3-review') AND goal='conversation'), 9, 'user', 'The {agenda} is planning the new quarter.', '議題は新しい四半期の計画。', 'agenda', (SELECT id FROM vocab_senses WHERE slug='agenda.n.itemlist'), ARRAY['agenda','workload','schedule','presentation']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u3-review') AND goal='conversation'), 10, 'npc', 'Exciting! Nervous at all?', 'わくわくだね！緊張してる？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u3-review') AND goal='conversation'), 11, 'user', 'A little, but I''ll {sort out} any problems as they come.', '少し、でも問題が出たら片付けるよ。', 'sort out', (SELECT id FROM vocab_senses WHERE slug='sort-out.phrv.resolve'), ARRAY['sort out','apply for','turn down','hand in']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u3-review') AND goal='conversation'), 12, 'npc', 'That''s the spirit.', 'その意気だね。', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u3-review') AND goal='conversation'), 13, 'user', 'I''ve already got my week''s {schedule} planned.', 'もう一週間の予定を立ててある。', 'schedule', (SELECT id FROM vocab_senses WHERE slug='schedule.n.timetable'), ARRAY['schedule','agenda','workload','presentation']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u3-review') AND goal='conversation'), 14, 'npc', 'So organized! You''ll do great, {{user_name}}.', 'しっかりしてる！うまくいくよ、{{user_name}}。', NULL, NULL, NULL);

-- Unit 4 review: After graduation
INSERT INTO vocab_lessons (slug, level_index, order_index, theme_id, title_en, title_ja, published, free) VALUES
  ('vocab-102-u4-review', 4, 90, (SELECT id FROM vocab_categories WHERE slug='university-life'), 'Review', '復習', TRUE, TRUE)
ON CONFLICT (slug) DO UPDATE SET level_index=EXCLUDED.level_index, order_index=EXCLUDED.order_index, theme_id=EXCLUDED.theme_id, title_en=EXCLUDED.title_en, title_ja=EXCLUDED.title_ja, published=EXCLUDED.published, free=EXCLUDED.free;
DELETE FROM vocab_lesson_items WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u4-review');
INSERT INTO vocab_lesson_items (lesson_id, sense_id, order_index)
SELECT (SELECT id FROM vocab_lessons WHERE slug='vocab-102-u4-review'), s.id, x.ord FROM (VALUES
  ('degree.n.qualification',0),('lecture.n.talk',1),('seminar.n.class',2),('assignment.n.task',3),('tutor.n.teacher',4),('campus.n.grounds',5),('graduate.v.finish',6),('scholarship.n.grant',7),('catch-up.phrv.reach',8),('fall-behind.phrv.lag',9),('keep-up.phrv.maintain',10),('go-over.phrv.review',11),('note-down.phrv.record',12),('take-in.phrv.absorb',13),('sign-up.phrv.enroll',14),('look-up.phrv.find',15),('skill.n.ability',16),('ability.n.capacity',17),('talent.n.gift',18),('knowledge.n.info',19),('experience.n.practice',20),('qualification.n.credential',21),('expert.n.specialist',22),('beginner.n.novice',23)
) AS x(slug, ord) JOIN vocab_senses s ON s.slug = x.slug ON CONFLICT DO NOTHING;
DELETE FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u4-review');
INSERT INTO vocab_scenes (lesson_id, goal, order_index, title_en, title_ja, setting, npc_role) VALUES
  ((SELECT id FROM vocab_lessons WHERE slug='vocab-102-u4-review'), 'conversation', 0, 'After graduation', '卒業のあと', 'cafe', 'friend');
INSERT INTO vocab_scene_lines (scene_id, order_index, speaker, text_en, text_ja, blank_answer, blank_sense_id, options) VALUES
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u4-review') AND goal='conversation'), 0, 'npc', 'You finally finished your studies!', 'ついに勉強を終えたね！', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u4-review') AND goal='conversation'), 1, 'user', 'Yes! I {graduate} officially next week.', 'うん！来週正式に卒業する。', 'graduate', (SELECT id FROM vocab_senses WHERE slug='graduate.v.finish'), ARRAY['graduate','sign up','catch up','keep up']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u4-review') AND goal='conversation'), 2, 'npc', 'Amazing. What was your subject?', 'すごい。専攻は何だった？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u4-review') AND goal='conversation'), 3, 'user', 'My {degree} is in marketing.', 'マーケティングの学位だよ。', 'degree', (SELECT id FROM vocab_senses WHERE slug='degree.n.qualification'), ARRAY['degree','lecture','campus','tutor']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u4-review') AND goal='conversation'), 4, 'npc', 'Was the final year hard?', '最終学年は大変だった？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u4-review') AND goal='conversation'), 5, 'user', 'Very. It was tough to {keep up} at times.', 'すごく。ときどきついていくのが大変だった。', 'keep up', (SELECT id FROM vocab_senses WHERE slug='keep-up.phrv.maintain'), ARRAY['keep up','sign up','look up','note down']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u4-review') AND goal='conversation'), 6, 'npc', 'But you managed.', 'でも乗り切ったね。', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u4-review') AND goal='conversation'), 7, 'user', 'I did. I had to {catch up} after being sick once.', 'うん。一度体調を崩して追いつく必要があった。', 'catch up', (SELECT id FROM vocab_senses WHERE slug='catch-up.phrv.reach'), ARRAY['catch up','sign up','look up','go over']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u4-review') AND goal='conversation'), 8, 'npc', 'So, job hunting now?', 'じゃあ今は就活？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u4-review') AND goal='conversation'), 9, 'user', 'Yes. Writing is my strongest {skill}.', 'うん。文章を書くのが一番のスキル。', 'skill', (SELECT id FROM vocab_senses WHERE slug='skill.n.ability'), ARRAY['skill','beginner','expert','qualification']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u4-review') AND goal='conversation'), 10, 'npc', 'That''s valuable everywhere.', 'どこでも役立つね。', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u4-review') AND goal='conversation'), 11, 'user', 'I also got some {experience} from an internship.', 'インターンで少し経験も積んだ。', 'experience', (SELECT id FROM vocab_senses WHERE slug='experience.n.practice'), ARRAY['experience','beginner','talent','expert']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u4-review') AND goal='conversation'), 12, 'npc', 'You''ll stand out.', '目立つよ。', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u4-review') AND goal='conversation'), 13, 'user', 'One day I''d love to be an {expert} in branding.', 'いつかブランディングの専門家になりたい。', 'expert', (SELECT id FROM vocab_senses WHERE slug='expert.n.specialist'), ARRAY['expert','beginner','talent','skill']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u4-review') AND goal='conversation'), 14, 'npc', 'You''ll get there, {{user_name}}.', 'きっとなれるよ、{{user_name}}。', NULL, NULL, NULL);

-- Unit 5 review: Money well managed
INSERT INTO vocab_lessons (slug, level_index, order_index, theme_id, title_en, title_ja, published, free) VALUES
  ('vocab-102-u5-review', 5, 90, (SELECT id FROM vocab_categories WHERE slug='managing-money'), 'Review', '復習', TRUE, TRUE)
ON CONFLICT (slug) DO UPDATE SET level_index=EXCLUDED.level_index, order_index=EXCLUDED.order_index, theme_id=EXCLUDED.theme_id, title_en=EXCLUDED.title_en, title_ja=EXCLUDED.title_ja, published=EXCLUDED.published, free=EXCLUDED.free;
DELETE FROM vocab_lesson_items WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u5-review');
INSERT INTO vocab_lesson_items (lesson_id, sense_id, order_index)
SELECT (SELECT id FROM vocab_lessons WHERE slug='vocab-102-u5-review'), s.id, x.ord FROM (VALUES
  ('budget.n.plan',0),('save-up.phrv.store',1),('afford.v.manage',2),('borrow.v.take',3),('lend.v.give',4),('owe.v.debt',5),('debt.n.money',6),('spend.v.pay',7),('pay-off.phrv.clear',8),('cut-back.phrv.reduce',9),('pay-back.phrv.repay',10),('run-out.phrv.deplete',11),('top-up.phrv.refill',12),('take-out.phrv.withdraw',13),('get-by.phrv.manage',14),('splash-out.phrv.spend',15),('bargain.n.deal',16),('discount.n.reduction',17),('sale.n.event',18),('voucher.n.coupon',19),('brand.n.make',20),('quality.n.standard',21),('secondhand.adj.used',22),('luxury.n.expensive',23)
) AS x(slug, ord) JOIN vocab_senses s ON s.slug = x.slug ON CONFLICT DO NOTHING;
DELETE FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u5-review');
INSERT INTO vocab_scenes (lesson_id, goal, order_index, title_en, title_ja, setting, npc_role) VALUES
  ((SELECT id FROM vocab_lessons WHERE slug='vocab-102-u5-review'), 'conversation', 0, 'Money well managed', '上手なやりくり', 'cafe', 'friend');
INSERT INTO vocab_scene_lines (scene_id, order_index, speaker, text_en, text_ja, blank_answer, blank_sense_id, options) VALUES
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u5-review') AND goal='conversation'), 0, 'npc', 'You seem more relaxed about money lately.', '最近お金に余裕がありそうだね。', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u5-review') AND goal='conversation'), 1, 'user', 'I finally stick to a {budget} now.', 'やっと予算を守れるようになった。', 'budget', (SELECT id FROM vocab_senses WHERE slug='budget.n.plan'), ARRAY['budget','debt','sale','discount']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u5-review') AND goal='conversation'), 2, 'npc', 'That''s great. Any big goals?', 'いいね。大きな目標は？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u5-review') AND goal='conversation'), 3, 'user', 'I''m trying to {save up} for a car.', '車のために貯金してる。', 'save up', (SELECT id FROM vocab_senses WHERE slug='save-up.phrv.store'), ARRAY['save up','spend','borrow','lend']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u5-review') AND goal='conversation'), 4, 'npc', 'Nice. Debt-free yet?', 'いいね。借金はもうない？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u5-review') AND goal='conversation'), 5, 'user', 'Almost! I just need to {pay off} one loan.', 'もう少し！あとローン一つ完済すれば。', 'pay off', (SELECT id FROM vocab_senses WHERE slug='pay-off.phrv.clear'), ARRAY['pay off','top up','splash out','take out']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u5-review') AND goal='conversation'), 6, 'npc', 'How did you manage it?', 'どうやりくりしたの？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u5-review') AND goal='conversation'), 7, 'user', 'I had to {cut back} on little luxuries.', 'ちょっとした贅沢を切り詰めた。', 'cut back', (SELECT id FROM vocab_senses WHERE slug='cut-back.phrv.reduce'), ARRAY['cut back','splash out','top up','run out']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u5-review') AND goal='conversation'), 8, 'npc', 'Worth it. Did you buy anything nice?', 'えらい。何かいいもの買った？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u5-review') AND goal='conversation'), 9, 'user', 'Just one thing, and it was a {bargain}.', '一つだけ、しかもお買い得だった。', 'bargain', (SELECT id FROM vocab_senses WHERE slug='bargain.n.deal'), ARRAY['bargain','brand','quality','luxury']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u5-review') AND goal='conversation'), 10, 'npc', 'Ooh, what was the deal?', 'へえ、どんなお得？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u5-review') AND goal='conversation'), 11, 'user', 'A winter coat with a huge {discount}.', '冬用のコートが大幅割引で。', 'discount', (SELECT id FROM vocab_senses WHERE slug='discount.n.reduction'), ARRAY['discount','brand','quality','voucher']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u5-review') AND goal='conversation'), 12, 'npc', 'Smart. Good coat?', '賢い。いいコート？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u5-review') AND goal='conversation'), 13, 'user', 'Yes, great {quality} for the price.', 'うん、値段の割に品質がいい。', 'quality', (SELECT id FROM vocab_senses WHERE slug='quality.n.standard'), ARRAY['quality','sale','discount','voucher']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u5-review') AND goal='conversation'), 14, 'npc', 'You''ve really got this, {{user_name}}.', '本当にしっかりしてるね、{{user_name}}。', NULL, NULL, NULL);

-- Unit 6 review: Visiting the new place
INSERT INTO vocab_lessons (slug, level_index, order_index, theme_id, title_en, title_ja, published, free) VALUES
  ('vocab-102-u6-review', 6, 90, (SELECT id FROM vocab_categories WHERE slug='housing'), 'Review', '復習', TRUE, TRUE)
ON CONFLICT (slug) DO UPDATE SET level_index=EXCLUDED.level_index, order_index=EXCLUDED.order_index, theme_id=EXCLUDED.theme_id, title_en=EXCLUDED.title_en, title_ja=EXCLUDED.title_ja, published=EXCLUDED.published, free=EXCLUDED.free;
DELETE FROM vocab_lesson_items WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u6-review');
INSERT INTO vocab_lesson_items (lesson_id, sense_id, order_index)
SELECT (SELECT id FROM vocab_lessons WHERE slug='vocab-102-u6-review'), s.id, x.ord FROM (VALUES
  ('rent.n.payment',0),('landlord.n.owner',1),('mortgage.n.loan',2),('furniture.n.items',3),('neighborhood.n.area',4),('suburb.n.outer',5),('spacious.adj.roomy',6),('cozy.adj.snug',7),('tidy-up.phrv.neaten',8),('throw-away.phrv.discard',9),('put-away.phrv.store',10),('clear-out.phrv.empty',11),('move-in.phrv.occupy',12),('settle-in.phrv.adjust',13),('plug-in.phrv.connect',14),('hang-up.phrv.hang',15),('leak.n.drip',16),('blocked.adj.clogged',17),('repair.v.fix',18),('plumber.n.worker',19),('electricity.n.power',20),('damage.n.harm',21),('flood.n.water',22),('spare.adj.extra',23)
) AS x(slug, ord) JOIN vocab_senses s ON s.slug = x.slug ON CONFLICT DO NOTHING;
DELETE FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u6-review');
INSERT INTO vocab_scenes (lesson_id, goal, order_index, title_en, title_ja, setting, npc_role) VALUES
  ((SELECT id FROM vocab_lessons WHERE slug='vocab-102-u6-review'), 'conversation', 0, 'Visiting the new place', '新居に遊びに行く', 'home', 'friend');
INSERT INTO vocab_scene_lines (scene_id, order_index, speaker, text_en, text_ja, blank_answer, blank_sense_id, options) VALUES
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u6-review') AND goal='conversation'), 0, 'npc', 'So this is your new place! Nice vibe.', 'ここが新居か！いい雰囲気。', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u6-review') AND goal='conversation'), 1, 'user', 'Thanks! The {rent} is great for the size.', 'ありがとう！広さの割に家賃が安い。', 'rent', (SELECT id FROM vocab_senses WHERE slug='rent.n.payment'), ARRAY['rent','landlord','mortgage','furniture']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u6-review') AND goal='conversation'), 2, 'npc', 'It feels really warm.', 'すごく暖かい感じ。', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u6-review') AND goal='conversation'), 3, 'user', 'Yeah, I made it {cozy} with lots of plants.', 'うん、植物をたくさん置いて居心地よくした。', 'cozy', (SELECT id FROM vocab_senses WHERE slug='cozy.adj.snug'), ARRAY['cozy','spacious','blocked','spare']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u6-review') AND goal='conversation'), 4, 'npc', 'It''s spotless too.', 'ピカピカだね。', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u6-review') AND goal='conversation'), 5, 'user', 'I {tidy up} a bit every morning.', '毎朝少しずつ片付けてる。', 'tidy up', (SELECT id FROM vocab_senses WHERE slug='tidy-up.phrv.neaten'), ARRAY['tidy up','throw away','plug in','hang up']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u6-review') AND goal='conversation'), 6, 'npc', 'Wish I could do that.', '私も見習いたい。', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u6-review') AND goal='conversation'), 7, 'user', 'Start by learning to {throw away} old stuff.', 'まず古い物を捨てることから。', 'throw away', (SELECT id FROM vocab_senses WHERE slug='throw-away.phrv.discard'), ARRAY['throw away','put away','plug in','hang up']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u6-review') AND goal='conversation'), 8, 'npc', 'Ha, true. Any problems with the flat?', 'はは、確かに。部屋の問題は？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u6-review') AND goal='conversation'), 9, 'user', 'One small {leak} under the sink.', 'シンクの下で小さな水漏れが一つ。', 'leak', (SELECT id FROM vocab_senses WHERE slug='leak.n.drip'), ARRAY['leak','damage','flood','spare']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u6-review') AND goal='conversation'), 10, 'npc', 'Did you fix it?', '直した？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u6-review') AND goal='conversation'), 11, 'user', 'A {plumber} came and sorted it.', '配管工が来て直してくれた。', 'plumber', (SELECT id FROM vocab_senses WHERE slug='plumber.n.worker'), ARRAY['plumber','landlord','damage','spare']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u6-review') AND goal='conversation'), 12, 'npc', 'So it''s all good now?', 'じゃあもう大丈夫？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u6-review') AND goal='conversation'), 13, 'user', 'Yes, one quick {repair} and it''s perfect.', 'うん、ちょっと修理したら完璧。', 'repair', (SELECT id FROM vocab_senses WHERE slug='repair.v.fix'), ARRAY['repair','leak','flood','spare']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u6-review') AND goal='conversation'), 14, 'npc', 'Love what you''ve done, {{user_name}}.', '素敵にしたね、{{user_name}}。', NULL, NULL, NULL);

-- Unit 7 review: Getting back on your feet
INSERT INTO vocab_lessons (slug, level_index, order_index, theme_id, title_en, title_ja, published, free) VALUES
  ('vocab-102-u7-review', 7, 90, (SELECT id FROM vocab_categories WHERE slug='wellbeing'), 'Review', '復習', TRUE, TRUE)
ON CONFLICT (slug) DO UPDATE SET level_index=EXCLUDED.level_index, order_index=EXCLUDED.order_index, theme_id=EXCLUDED.theme_id, title_en=EXCLUDED.title_en, title_ja=EXCLUDED.title_ja, published=EXCLUDED.published, free=EXCLUDED.free;
DELETE FROM vocab_lesson_items WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u7-review');
INSERT INTO vocab_lesson_items (lesson_id, sense_id, order_index)
SELECT (SELECT id FROM vocab_lessons WHERE slug='vocab-102-u7-review'), s.id, x.ord FROM (VALUES
  ('exercise.n.activity',0),('diet.n.food',1),('healthy.adj.well',2),('energy.n.vigor',3),('stress.n.pressure',4),('relax.v.rest',5),('habit.n.routine',6),('lifestyle.n.way',7),('work-out.phrv.exercise',8),('give-up.phrv.quit',9),('cut-down.phrv.reduce',10),('warm-up.phrv.prepare',11),('put-on.phrv.gain',12),('slow-down.phrv.decelerate',13),('take-up.phrv.start',14),('ease-off.phrv.reduce',15),('symptom.n.sign',16),('prescription.n.paper',17),('treatment.n.care',18),('injury.n.harm',19),('recover.v.heal',20),('painkiller.n.medicine',21),('allergy.n.reaction',22),('dizzy.adj.faint',23)
) AS x(slug, ord) JOIN vocab_senses s ON s.slug = x.slug ON CONFLICT DO NOTHING;
DELETE FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u7-review');
INSERT INTO vocab_scenes (lesson_id, goal, order_index, title_en, title_ja, setting, npc_role) VALUES
  ((SELECT id FROM vocab_lessons WHERE slug='vocab-102-u7-review'), 'conversation', 0, 'Getting back on your feet', '元気を取り戻す', 'cafe', 'friend');
INSERT INTO vocab_scene_lines (scene_id, order_index, speaker, text_en, text_ja, blank_answer, blank_sense_id, options) VALUES
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u7-review') AND goal='conversation'), 0, 'npc', 'How are you feeling after the flu?', 'インフルのあと、体調どう？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u7-review') AND goal='conversation'), 1, 'user', 'Much better, I''m starting to {recover}.', 'だいぶいい、回復してきてる。', 'recover', (SELECT id FROM vocab_senses WHERE slug='recover.v.heal'), ARRAY['recover','symptom','treatment','injury']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u7-review') AND goal='conversation'), 2, 'npc', 'Good. Was it rough?', 'よかった。つらかった？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u7-review') AND goal='conversation'), 3, 'user', 'Yeah, the worst {symptom} was the fever.', 'うん、一番つらい症状は熱だった。', 'symptom', (SELECT id FROM vocab_senses WHERE slug='symptom.n.sign'), ARRAY['symptom','treatment','painkiller','allergy']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u7-review') AND goal='conversation'), 4, 'npc', 'Did the doctor help?', '医者は役に立った？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u7-review') AND goal='conversation'), 5, 'user', 'Yes, a simple {treatment} and lots of rest.', 'うん、簡単な治療とたっぷりの休養。', 'treatment', (SELECT id FROM vocab_senses WHERE slug='treatment.n.care'), ARRAY['treatment','symptom','allergy','injury']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u7-review') AND goal='conversation'), 6, 'npc', 'Are you back to normal now?', 'もう元通り？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u7-review') AND goal='conversation'), 7, 'user', 'Almost. I''m easing back into {exercise}.', 'ほぼ。少しずつ運動を再開してる。', 'exercise', (SELECT id FROM vocab_senses WHERE slug='exercise.n.activity'), ARRAY['exercise','diet','energy','stress']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u7-review') AND goal='conversation'), 8, 'npc', 'Don''t overdo it.', '無理しないで。', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u7-review') AND goal='conversation'), 9, 'user', 'I only {work out} lightly for now.', '今は軽く運動するだけ。', 'work out', (SELECT id FROM vocab_senses WHERE slug='work-out.phrv.exercise'), ARRAY['work out','give up','cut down','warm up']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u7-review') AND goal='conversation'), 10, 'npc', 'Wise. Anything else changing?', '賢明。他に変えたことは？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u7-review') AND goal='conversation'), 11, 'user', 'I decided to {give up} junk food.', 'ジャンクフードをやめることにした。', 'give up', (SELECT id FROM vocab_senses WHERE slug='give-up.phrv.quit'), ARRAY['give up','warm up','take up','put on']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u7-review') AND goal='conversation'), 12, 'npc', 'That''ll help your recovery.', '回復に効くよ。', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u7-review') AND goal='conversation'), 13, 'user', 'And less {stress} means better sleep.', 'それにストレスが減れば睡眠もよくなる。', 'stress', (SELECT id FROM vocab_senses WHERE slug='stress.n.pressure'), ARRAY['stress','energy','diet','habit']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u7-review') AND goal='conversation'), 14, 'npc', 'Take care of yourself, {{user_name}}.', '体を大事にね、{{user_name}}。', NULL, NULL, NULL);

-- Unit 8 review: Off again soon
INSERT INTO vocab_lessons (slug, level_index, order_index, theme_id, title_en, title_ja, published, free) VALUES
  ('vocab-102-u8-review', 8, 90, (SELECT id FROM vocab_categories WHERE slug='planning-a-trip'), 'Review', '復習', TRUE, TRUE)
ON CONFLICT (slug) DO UPDATE SET level_index=EXCLUDED.level_index, order_index=EXCLUDED.order_index, theme_id=EXCLUDED.theme_id, title_en=EXCLUDED.title_en, title_ja=EXCLUDED.title_ja, published=EXCLUDED.published, free=EXCLUDED.free;
DELETE FROM vocab_lesson_items WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u8-review');
INSERT INTO vocab_lesson_items (lesson_id, sense_id, order_index)
SELECT (SELECT id FROM vocab_lessons WHERE slug='vocab-102-u8-review'), s.id, x.ord FROM (VALUES
  ('destination.n.place',0),('itinerary.n.plan',1),('accommodation.n.lodging',2),('reserve.v.book',3),('abroad.adv.overseas',4),('journey.n.trip',5),('luggage.n.bags',6),('insurance.n.cover',7),('set-off.phrv.depart',8),('get-around.phrv.travel',9),('drop-off.phrv.deliver',10),('pick-up.phrv.collect',11),('hurry-up.phrv.hasten',12),('take-off.phrv.depart',13),('get-on.phrv.board',14),('hold-up.phrv.delay',15),('currency.n.money',16),('exchange.v.swap',17),('customs.n.border',18),('visa.n.permit',19),('jetlag.n.tiredness',20),('crowded.adj.busy',21),('stranded.adj.stuck',22),('departure.n.leaving',23)
) AS x(slug, ord) JOIN vocab_senses s ON s.slug = x.slug ON CONFLICT DO NOTHING;
DELETE FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u8-review');
INSERT INTO vocab_scenes (lesson_id, goal, order_index, title_en, title_ja, setting, npc_role) VALUES
  ((SELECT id FROM vocab_lessons WHERE slug='vocab-102-u8-review'), 'conversation', 0, 'Off again soon', 'また旅立つ', 'cafe', 'friend');
INSERT INTO vocab_scene_lines (scene_id, order_index, speaker, text_en, text_ja, blank_answer, blank_sense_id, options) VALUES
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u8-review') AND goal='conversation'), 0, 'npc', 'So, where are you off to next?', '次はどこへ行くの？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u8-review') AND goal='conversation'), 1, 'user', 'My next {destination} is Thailand.', '次の目的地はタイ。', 'destination', (SELECT id FROM vocab_senses WHERE slug='destination.n.place'), ARRAY['destination','journey','luggage','insurance']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u8-review') AND goal='conversation'), 2, 'npc', 'Nice! All booked?', 'いいね！予約済み？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u8-review') AND goal='conversation'), 3, 'user', 'Yes, just packing my {luggage} now.', 'うん、今荷物を詰めてる。', 'luggage', (SELECT id FROM vocab_senses WHERE slug='luggage.n.bags'), ARRAY['luggage','journey','destination','insurance']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u8-review') AND goal='conversation'), 4, 'npc', 'What time do you leave?', '何時に出発？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u8-review') AND goal='conversation'), 5, 'user', 'I {set off} at dawn tomorrow.', '明日の夜明けに出発する。', 'set off', (SELECT id FROM vocab_senses WHERE slug='set-off.phrv.depart'), ARRAY['set off','get around','pick up','drop off']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u8-review') AND goal='conversation'), 6, 'npc', 'Need a lift to the airport?', '空港まで送ろうか？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u8-review') AND goal='conversation'), 7, 'user', 'Could you {pick up} me at six?', '6時に拾ってくれる？', 'pick up', (SELECT id FROM vocab_senses WHERE slug='pick-up.phrv.collect'), ARRAY['pick up','drop off','hurry up','hold up']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u8-review') AND goal='conversation'), 8, 'npc', 'Of course. Last trip go okay?', 'もちろん。前回の旅行は大丈夫だった？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u8-review') AND goal='conversation'), 9, 'user', 'Yeah, though the {jetlag} was brutal.', 'うん、でも時差ぼけがひどかった。', 'jetlag', (SELECT id FROM vocab_senses WHERE slug='jetlag.n.tiredness'), ARRAY['jetlag','currency','customs','visa']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u8-review') AND goal='conversation'), 10, 'npc', 'Border stuff smooth?', '入国はスムーズ？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u8-review') AND goal='conversation'), 11, 'user', 'Mostly. {customs} was slow but fine.', 'だいたい。税関は遅いけど問題なし。', 'customs', (SELECT id FROM vocab_senses WHERE slug='customs.n.border'), ARRAY['customs','currency','visa','departure']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u8-review') AND goal='conversation'), 12, 'npc', 'Got local money sorted?', '現地のお金は用意した？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u8-review') AND goal='conversation'), 13, 'user', 'I''ll get the {currency} at the airport again.', 'また空港で通貨を手に入れる。', 'currency', (SELECT id FROM vocab_senses WHERE slug='currency.n.money'), ARRAY['currency','customs','visa','departure']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u8-review') AND goal='conversation'), 14, 'npc', 'Have an amazing trip, {{user_name}}!', '素敵な旅を、{{user_name}}！', NULL, NULL, NULL);

-- Unit 9 review: Getting online
INSERT INTO vocab_lessons (slug, level_index, order_index, theme_id, title_en, title_ja, published, free) VALUES
  ('vocab-102-u9-review', 9, 90, (SELECT id FROM vocab_categories WHERE slug='devices-online'), 'Review', '復習', TRUE, TRUE)
ON CONFLICT (slug) DO UPDATE SET level_index=EXCLUDED.level_index, order_index=EXCLUDED.order_index, theme_id=EXCLUDED.theme_id, title_en=EXCLUDED.title_en, title_ja=EXCLUDED.title_ja, published=EXCLUDED.published, free=EXCLUDED.free;
DELETE FROM vocab_lesson_items WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u9-review');
INSERT INTO vocab_lesson_items (lesson_id, sense_id, order_index)
SELECT (SELECT id FROM vocab_lessons WHERE slug='vocab-102-u9-review'), s.id, x.ord FROM (VALUES
  ('device.n.machine',0),('gadget.n.tool',1),('update.n.version',2),('download.v.get',3),('upload.v.send',4),('wifi.n.internet',5),('charger.n.cable',6),('storage.n.space',7),('log-in.phrv.access',8),('log-out.phrv.exit',9),('set-up.phrv.configure',10),('back-up.phrv.copy',11),('switch-on.phrv.start',12),('switch-off.phrv.stop',13),('scroll.v.move',14),('zoom-in.phrv.enlarge',15),('post.v.publish',16),('share.v.spread',17),('follow.v.subscribe',18),('comment.n.remark',19),('viral.adj.spreading',20),('headline.n.title',21),('subscribe.v.join',22),('notification.n.alert',23)
) AS x(slug, ord) JOIN vocab_senses s ON s.slug = x.slug ON CONFLICT DO NOTHING;
DELETE FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u9-review');
INSERT INTO vocab_scenes (lesson_id, goal, order_index, title_en, title_ja, setting, npc_role) VALUES
  ((SELECT id FROM vocab_lessons WHERE slug='vocab-102-u9-review'), 'conversation', 0, 'Getting online', 'ネットを始める', 'cafe', 'friend');
INSERT INTO vocab_scene_lines (scene_id, order_index, speaker, text_en, text_ja, blank_answer, blank_sense_id, options) VALUES
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u9-review') AND goal='conversation'), 0, 'npc', 'Finally joined social media?', 'ついにSNS始めた？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u9-review') AND goal='conversation'), 1, 'user', 'Yeah, once I got this new {device}.', 'うん、この新しい端末を買ってから。', 'device', (SELECT id FROM vocab_senses WHERE slug='device.n.machine'), ARRAY['device','gadget','charger','storage']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u9-review') AND goal='conversation'), 2, 'npc', 'Connected okay?', 'ちゃんとつながった？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u9-review') AND goal='conversation'), 3, 'user', 'Yes, the home {wifi} works great.', 'うん、家のWi-Fiが快調。', 'wifi', (SELECT id FROM vocab_senses WHERE slug='wifi.n.internet'), ARRAY['wifi','storage','charger','update']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u9-review') AND goal='conversation'), 4, 'npc', 'Did you make an account?', 'アカウント作った？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u9-review') AND goal='conversation'), 5, 'user', 'I can {log in} with my email now.', 'メールでログインできるようになった。', 'log in', (SELECT id FROM vocab_senses WHERE slug='log-in.phrv.access'), ARRAY['log in','log out','switch off','back up']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u9-review') AND goal='conversation'), 6, 'npc', 'Smart to protect your data.', 'データを守るのは賢い。', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u9-review') AND goal='conversation'), 7, 'user', 'I {back up} my photos to the cloud too.', '写真もクラウドにバックアップしてる。', 'back up', (SELECT id FROM vocab_senses WHERE slug='back-up.phrv.copy'), ARRAY['back up','log out','switch off','zoom in']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u9-review') AND goal='conversation'), 8, 'npc', 'So, posting yet?', 'で、もう投稿した？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u9-review') AND goal='conversation'), 9, 'user', 'I made my first {post} yesterday!', '昨日、初投稿した！', 'post', (SELECT id FROM vocab_senses WHERE slug='post.v.publish'), ARRAY['post','comment','headline','notification']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u9-review') AND goal='conversation'), 10, 'npc', 'How did it do?', '反応どうだった？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u9-review') AND goal='conversation'), 11, 'user', 'Surprisingly, it nearly went {viral}.', '意外にも、ほぼバズった。', 'viral', (SELECT id FROM vocab_senses WHERE slug='viral.adj.spreading'), ARRAY['viral','post','comment','headline']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u9-review') AND goal='conversation'), 12, 'npc', 'Wow! Gaining fans?', 'わあ！ファン増えてる？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u9-review') AND goal='conversation'), 13, 'user', 'A few people started to {follow} me.', '何人かフォローし始めてくれた。', 'follow', (SELECT id FROM vocab_senses WHERE slug='follow.v.subscribe'), ARRAY['follow','share','post','subscribe']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u9-review') AND goal='conversation'), 14, 'npc', 'Look at you go, {{user_name}}!', 'やるね、{{user_name}}！', NULL, NULL, NULL);

-- Unit 10 review: Dinner decisions
INSERT INTO vocab_lessons (slug, level_index, order_index, theme_id, title_en, title_ja, published, free) VALUES
  ('vocab-102-u10-review', 10, 90, (SELECT id FROM vocab_categories WHERE slug='eating-out'), 'Review', '復習', TRUE, TRUE)
ON CONFLICT (slug) DO UPDATE SET level_index=EXCLUDED.level_index, order_index=EXCLUDED.order_index, theme_id=EXCLUDED.theme_id, title_en=EXCLUDED.title_en, title_ja=EXCLUDED.title_ja, published=EXCLUDED.published, free=EXCLUDED.free;
DELETE FROM vocab_lesson_items WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u10-review');
INSERT INTO vocab_lesson_items (lesson_id, sense_id, order_index)
SELECT (SELECT id FROM vocab_lessons WHERE slug='vocab-102-u10-review'), s.id, x.ord FROM (VALUES
  ('reservation.n.booking',0),('starter.n.appetizer',1),('dessert.n.sweet',2),('tip.n.gratuity',3),('waiter.n.server',4),('cuisine.n.cooking',5),('vegetarian.n.diet',6),('menu.n.list',7),('ingredient.n.item',8),('chop.v.cut',9),('stir.v.mix',10),('bake.v.oven',11),('roast.v.oven2',12),('spicy.adj.hot',13),('flavor.n.taste',14),('leftovers.n.remains',15),('eat-out.phrv.dine',16),('heat-up.phrv.warm',17),('cut-up.phrv.slice',18),('wash-up.phrv.clean',19),('snack.n.food',20),('craving.n.desire',21),('starving.adj.hungry',22),('tasty.adj.delicious',23)
) AS x(slug, ord) JOIN vocab_senses s ON s.slug = x.slug ON CONFLICT DO NOTHING;
DELETE FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u10-review');
INSERT INTO vocab_scenes (lesson_id, goal, order_index, title_en, title_ja, setting, npc_role) VALUES
  ((SELECT id FROM vocab_lessons WHERE slug='vocab-102-u10-review'), 'conversation', 0, 'Dinner decisions', '夕飯どうする', 'home', 'friend');
INSERT INTO vocab_scene_lines (scene_id, order_index, speaker, text_en, text_ja, blank_answer, blank_sense_id, options) VALUES
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u10-review') AND goal='conversation'), 0, 'npc', 'I''m hungry. Dinner plan?', 'お腹すいた。夕飯どうする？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u10-review') AND goal='conversation'), 1, 'user', 'Same, I''m {starving}.', '私も、腹ぺこ。', 'starving', (SELECT id FROM vocab_senses WHERE slug='starving.adj.hungry'), ARRAY['starving','tasty','snack','craving']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u10-review') AND goal='conversation'), 2, 'npc', 'Cook or go out?', '作る？外食？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u10-review') AND goal='conversation'), 3, 'user', 'Let''s {eat out} tonight.', '今夜は外食しよう。', 'eat out', (SELECT id FROM vocab_senses WHERE slug='eat-out.phrv.dine'), ARRAY['eat out','heat up','cut up','wash up']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u10-review') AND goal='conversation'), 4, 'npc', 'Where to?', 'どこに？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u10-review') AND goal='conversation'), 5, 'user', 'That Thai place; I''ll make a {reservation}.', 'あのタイ料理店、予約するね。', 'reservation', (SELECT id FROM vocab_senses WHERE slug='reservation.n.booking'), ARRAY['reservation','starter','dessert','tip']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u10-review') AND goal='conversation'), 6, 'npc', 'Do they have veggie options?', 'ベジタリアン向けある？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u10-review') AND goal='conversation'), 7, 'user', 'Yes, their {menu} has lots.', 'うん、メニューに色々ある。', 'menu', (SELECT id FROM vocab_senses WHERE slug='menu.n.list'), ARRAY['menu','tip','starter','dessert']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u10-review') AND goal='conversation'), 8, 'npc', 'Is the food good?', '味はいい？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u10-review') AND goal='conversation'), 9, 'user', 'So {tasty}, you''ll love it.', 'すごくおいしい、絶対気に入る。', 'tasty', (SELECT id FROM vocab_senses WHERE slug='tasty.adj.delicious'), ARRAY['tasty','snack','starving','craving']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u10-review') AND goal='conversation'), 10, 'npc', 'Is it very hot?', 'かなり辛い？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u10-review') AND goal='conversation'), 11, 'user', 'You can ask for less {spicy}.', '辛さ控えめにお願いできるよ。', 'spicy', (SELECT id FROM vocab_senses WHERE slug='spicy.adj.hot'), ARRAY['spicy','flavor','ingredient','leftovers']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u10-review') AND goal='conversation'), 12, 'npc', 'Great. What''s their specialty?', 'いいね。名物は？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u10-review') AND goal='conversation'), 13, 'user', 'Fresh lemongrass is the key {ingredient}.', '新鮮なレモングラスが決め手の材料。', 'ingredient', (SELECT id FROM vocab_senses WHERE slug='ingredient.n.item'), ARRAY['ingredient','flavor','leftovers','chop']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u10-review') AND goal='conversation'), 14, 'npc', 'Let''s go, {{user_name}}!', '行こう、{{user_name}}！', NULL, NULL, NULL);

-- Unit 11 review: The new neighborhood
INSERT INTO vocab_lessons (slug, level_index, order_index, theme_id, title_en, title_ja, published, free) VALUES
  ('vocab-102-u11-review', 11, 90, (SELECT id FROM vocab_categories WHERE slug='in-the-city'), 'Review', '復習', TRUE, TRUE)
ON CONFLICT (slug) DO UPDATE SET level_index=EXCLUDED.level_index, order_index=EXCLUDED.order_index, theme_id=EXCLUDED.theme_id, title_en=EXCLUDED.title_en, title_ja=EXCLUDED.title_ja, published=EXCLUDED.published, free=EXCLUDED.free;
DELETE FROM vocab_lesson_items WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u11-review');
INSERT INTO vocab_lesson_items (lesson_id, sense_id, order_index)
SELECT (SELECT id FROM vocab_lessons WHERE slug='vocab-102-u11-review'), s.id, x.ord FROM (VALUES
  ('traffic.n.cars',0),('pedestrian.n.walker',1),('crossing.n.place',2),('pavement.n.walkway',3),('commute.v.travel',4),('parking.n.space',5),('junction.n.crossing',6),('roadworks.n.repair',7),('forecast.n.prediction',8),('humid.adj.damp',9),('freezing.adj.cold',10),('storm.n.weather',11),('thunder.n.sound',12),('breeze.n.wind',13),('foggy.adj.misty',14),('mild.adj.gentle',15),('pollution.n.dirt',16),('recycle.v.reuse',17),('waste.n.rubbish',18),('litter.n.trash',19),('climate.n.weather',20),('sustainable.adj.green',21),('protect.v.guard',22),('clean-up.phrv.tidy',23)
) AS x(slug, ord) JOIN vocab_senses s ON s.slug = x.slug ON CONFLICT DO NOTHING;
DELETE FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u11-review');
INSERT INTO vocab_scenes (lesson_id, goal, order_index, title_en, title_ja, setting, npc_role) VALUES
  ((SELECT id FROM vocab_lessons WHERE slug='vocab-102-u11-review'), 'conversation', 0, 'The new neighborhood', '新しい街で', 'cafe', 'friend');
INSERT INTO vocab_scene_lines (scene_id, order_index, speaker, text_en, text_ja, blank_answer, blank_sense_id, options) VALUES
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u11-review') AND goal='conversation'), 0, 'npc', 'How''s the new neighborhood?', '新しい街はどう？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u11-review') AND goal='conversation'), 1, 'user', 'Good, though the {traffic} is noisy.', 'いいけど、交通の音がうるさい。', 'traffic', (SELECT id FROM vocab_senses WHERE slug='traffic.n.cars'), ARRAY['traffic','parking','crossing','junction']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u11-review') AND goal='conversation'), 2, 'npc', 'Long way to work?', '通勤は長い？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u11-review') AND goal='conversation'), 3, 'user', 'I {commute} thirty minutes by train.', '電車で30分通勤してる。', 'commute', (SELECT id FROM vocab_senses WHERE slug='commute.v.travel'), ARRAY['commute','crossing','parking','roadworks']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u11-review') AND goal='conversation'), 4, 'npc', 'Not bad. Weather okay today?', '悪くないね。今日の天気は？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u11-review') AND goal='conversation'), 5, 'user', 'The {forecast} says sunny later.', '予報だと後で晴れ。', 'forecast', (SELECT id FROM vocab_senses WHERE slug='forecast.n.prediction'), ARRAY['forecast','breeze','thunder','storm']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u11-review') AND goal='conversation'), 6, 'npc', 'No rain this week?', '今週は雨なし？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u11-review') AND goal='conversation'), 7, 'user', 'One {storm} on Thursday, they say.', '木曜に嵐が一回だって。', 'storm', (SELECT id FROM vocab_senses WHERE slug='storm.n.weather'), ARRAY['storm','breeze','forecast','thunder']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u11-review') AND goal='conversation'), 8, 'npc', 'By the way, is your area clean?', 'ところで、その辺はきれい？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u11-review') AND goal='conversation'), 9, 'user', 'Mostly, but there''s some {litter} in the park.', 'だいたい、でも公園に少しごみがある。', 'litter', (SELECT id FROM vocab_senses WHERE slug='litter.n.trash'), ARRAY['litter','waste','pollution','climate']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u11-review') AND goal='conversation'), 10, 'npc', 'Do people help?', 'みんな協力してる？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u11-review') AND goal='conversation'), 11, 'user', 'Yes, everyone tries to {recycle} here.', 'うん、みんなリサイクルを心がけてる。', 'recycle', (SELECT id FROM vocab_senses WHERE slug='recycle.v.reuse'), ARRAY['recycle','protect','clean up','waste']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u11-review') AND goal='conversation'), 12, 'npc', 'That''s a good community.', 'いいコミュニティだね。', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u11-review') AND goal='conversation'), 13, 'user', 'We all want to {protect} the area.', 'みんなこの地域を守りたいんだ。', 'protect', (SELECT id FROM vocab_senses WHERE slug='protect.v.guard'), ARRAY['protect','recycle','clean up','waste']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u11-review') AND goal='conversation'), 14, 'npc', 'Lucky you, {{user_name}}.', 'いいね、{{user_name}}。', NULL, NULL, NULL);

-- Unit 12 review: So many interests
INSERT INTO vocab_lessons (slug, level_index, order_index, theme_id, title_en, title_ja, published, free) VALUES
  ('vocab-102-u12-review', 12, 90, (SELECT id FROM vocab_categories WHERE slug='hobbies-interests'), 'Review', '復習', TRUE, TRUE)
ON CONFLICT (slug) DO UPDATE SET level_index=EXCLUDED.level_index, order_index=EXCLUDED.order_index, theme_id=EXCLUDED.theme_id, title_en=EXCLUDED.title_en, title_ja=EXCLUDED.title_ja, published=EXCLUDED.published, free=EXCLUDED.free;
DELETE FROM vocab_lesson_items WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u12-review');
INSERT INTO vocab_lesson_items (lesson_id, sense_id, order_index)
SELECT (SELECT id FROM vocab_lessons WHERE slug='vocab-102-u12-review'), s.id, x.ord FROM (VALUES
  ('get-into.phrv.enjoy',0),('carry-on.phrv.continue',1),('take-part.phrv.participate',2),('join-in.phrv.participate2',3),('come-along.phrv.accompany',4),('work-on.phrv.improve',5),('show-off.phrv.display',6),('try-out.phrv.test',7),('exhibition.n.show',8),('gallery.n.place',9),('novel.n.book',10),('author.n.writer',11),('director.n.filmmaker',12),('plot.n.story',13),('audience.n.viewers',14),('review.n.critique',15),('venue.n.place',16),('crowd.n.people',17),('queue.n.line',18),('festival.n.event',19),('gig.n.concert',20),('encore.n.extra',21),('backstage.adv.behind',22),('lineup.n.acts',23)
) AS x(slug, ord) JOIN vocab_senses s ON s.slug = x.slug ON CONFLICT DO NOTHING;
DELETE FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u12-review');
INSERT INTO vocab_scenes (lesson_id, goal, order_index, title_en, title_ja, setting, npc_role) VALUES
  ((SELECT id FROM vocab_lessons WHERE slug='vocab-102-u12-review'), 'conversation', 0, 'So many interests', '興味いろいろ', 'cafe', 'friend');
INSERT INTO vocab_scene_lines (scene_id, order_index, speaker, text_en, text_ja, blank_answer, blank_sense_id, options) VALUES
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u12-review') AND goal='conversation'), 0, 'npc', 'You seem to have lots of hobbies now.', '最近趣味が多いね。', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u12-review') AND goal='conversation'), 1, 'user', 'Yeah, I really {get into} new things lately.', 'うん、最近いろいろハマってる。', 'get into', (SELECT id FROM vocab_senses WHERE slug='get-into.phrv.enjoy'), ARRAY['get into','carry on','show off','work on']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u12-review') AND goal='conversation'), 2, 'npc', 'Like what?', '例えば？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u12-review') AND goal='conversation'), 3, 'user', 'I love to {try out} different activities.', 'いろんな活動を試すのが好き。', 'try out', (SELECT id FROM vocab_senses WHERE slug='try-out.phrv.test'), ARRAY['try out','carry on','show off','join in']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u12-review') AND goal='conversation'), 4, 'npc', 'Reading too?', '読書も？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u12-review') AND goal='conversation'), 5, 'user', 'Yes, I just finished a great {novel}.', 'うん、いい小説を読み終えたばかり。', 'novel', (SELECT id FROM vocab_senses WHERE slug='novel.n.book'), ARRAY['novel','author','plot','review']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u12-review') AND goal='conversation'), 6, 'npc', 'Who''s it by?', '誰の作品？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u12-review') AND goal='conversation'), 7, 'user', 'A new {author} everyone''s talking about.', 'みんなが話題にしてる新しい著者。', 'author', (SELECT id FROM vocab_senses WHERE slug='author.n.writer'), ARRAY['author','plot','review','gallery']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u12-review') AND goal='conversation'), 8, 'npc', 'Worth reading?', '読む価値ある？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u12-review') AND goal='conversation'), 9, 'user', 'Every {review} says yes.', 'どのレビューも高評価。', 'review', (SELECT id FROM vocab_senses WHERE slug='review.n.critique'), ARRAY['review','author','plot','gallery']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u12-review') AND goal='conversation'), 10, 'npc', 'Doing anything fun this weekend?', '週末は何か楽しいこと？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u12-review') AND goal='conversation'), 11, 'user', 'A {gig} by my favorite band!', '大好きなバンドのライブ！', 'gig', (SELECT id FROM vocab_senses WHERE slug='gig.n.concert'), ARRAY['gig','venue','crowd','queue']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u12-review') AND goal='conversation'), 12, 'npc', 'Big show?', '大きなショー？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u12-review') AND goal='conversation'), 13, 'user', 'A massive {crowd} is coming.', '大勢の観客が来る。', 'crowd', (SELECT id FROM vocab_senses WHERE slug='crowd.n.people'), ARRAY['crowd','venue','queue','encore']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u12-review') AND goal='conversation'), 14, 'npc', 'Have fun, {{user_name}}!', '楽しんで、{{user_name}}！', NULL, NULL, NULL);

-- Unit 13 review: Sorting out a mess
INSERT INTO vocab_lessons (slug, level_index, order_index, theme_id, title_en, title_ja, published, free) VALUES
  ('vocab-102-u13-review', 13, 90, (SELECT id FROM vocab_categories WHERE slug='complaints-service'), 'Review', '復習', TRUE, TRUE)
ON CONFLICT (slug) DO UPDATE SET level_index=EXCLUDED.level_index, order_index=EXCLUDED.order_index, theme_id=EXCLUDED.theme_id, title_en=EXCLUDED.title_en, title_ja=EXCLUDED.title_ja, published=EXCLUDED.published, free=EXCLUDED.free;
DELETE FROM vocab_lesson_items WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u13-review');
INSERT INTO vocab_lesson_items (lesson_id, sense_id, order_index)
SELECT (SELECT id FROM vocab_lessons WHERE slug='vocab-102-u13-review'), s.id, x.ord FROM (VALUES
  ('deal-with.phrv.handle',0),('get-back.phrv.reply',1),('follow-up.phrv.check',2),('chase-up.phrv.pursue',3),('take-back.phrv.return',4),('own-up.phrv.admit',5),('bring-up.phrv.mention',6),('point-out.phrv.indicate',7),('fault.n.defect',8),('guarantee.n.promise',9),('warranty.n.cover',10),('faulty.adj.broken',11),('complaint.n.grievance',12),('defective.adj.flawed',13),('compensation.n.payment',14),('dodgy.adj.suspect',15),('application.n.form',16),('document.n.paper',17),('certificate.n.proof',18),('approve.v.accept',19),('reject.v.refuse',20),('submit.v.hand',21),('procedure.n.steps',22),('requirement.n.need',23)
) AS x(slug, ord) JOIN vocab_senses s ON s.slug = x.slug ON CONFLICT DO NOTHING;
DELETE FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u13-review');
INSERT INTO vocab_scenes (lesson_id, goal, order_index, title_en, title_ja, setting, npc_role) VALUES
  ((SELECT id FROM vocab_lessons WHERE slug='vocab-102-u13-review'), 'conversation', 0, 'Sorting out a mess', 'トラブルの後始末', 'cafe', 'friend');
INSERT INTO vocab_scene_lines (scene_id, order_index, speaker, text_en, text_ja, blank_answer, blank_sense_id, options) VALUES
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u13-review') AND goal='conversation'), 0, 'npc', 'Did you sort out the broken laptop?', '壊れたノートPC、解決した？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u13-review') AND goal='conversation'), 1, 'user', 'Almost. It took ages to {deal with} the store.', 'もう少し。店との対応にすごく時間がかかった。', 'deal with', (SELECT id FROM vocab_senses WHERE slug='deal-with.phrv.handle'), ARRAY['deal with','get back','own up','point out']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u13-review') AND goal='conversation'), 2, 'npc', 'Was it broken from the start?', '最初から壊れてた？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u13-review') AND goal='conversation'), 3, 'user', 'Yeah, it was {faulty} on day one.', 'うん、初日から不良だった。', 'faulty', (SELECT id FROM vocab_senses WHERE slug='faulty.adj.broken'), ARRAY['faulty','complaint','warranty','fault']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u13-review') AND goal='conversation'), 4, 'npc', 'Did you complain?', '苦情は言った？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u13-review') AND goal='conversation'), 5, 'user', 'I filed a {complaint} right away.', 'すぐに苦情を出した。', 'complaint', (SELECT id FROM vocab_senses WHERE slug='complaint.n.grievance'), ARRAY['complaint','warranty','compensation','guarantee']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u13-review') AND goal='conversation'), 6, 'npc', 'Did they respond?', '返事あった？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u13-review') AND goal='conversation'), 7, 'user', 'I had to {follow up} twice to get a reply.', '返事をもらうのに2回追って確認した。', 'follow up', (SELECT id FROM vocab_senses WHERE slug='follow-up.phrv.check'), ARRAY['follow up','own up','take back','bring up']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u13-review') AND goal='conversation'), 8, 'npc', 'Refund needs forms, right?', '返金には書類が要るよね？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u13-review') AND goal='conversation'), 9, 'user', 'Yes, I sent a {document} with the receipt.', 'うん、領収書と一緒に書類を送った。', 'document', (SELECT id FROM vocab_senses WHERE slug='document.n.paper'), ARRAY['document','application','certificate','procedure']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u13-review') AND goal='conversation'), 10, 'npc', 'Did you send it off?', 'もう提出した？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u13-review') AND goal='conversation'), 11, 'user', 'I''ll {submit} the claim online tonight.', '今夜オンラインで申請を提出する。', 'submit', (SELECT id FROM vocab_senses WHERE slug='submit.v.hand'), ARRAY['submit','approve','reject','document']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u13-review') AND goal='conversation'), 12, 'npc', 'Hope they say yes fast.', '早く承認されるといいね。', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u13-review') AND goal='conversation'), 13, 'user', 'If they {approve} it, I get my money back.', '承認されればお金が戻る。', 'approve', (SELECT id FROM vocab_senses WHERE slug='approve.v.accept'), ARRAY['approve','reject','submit','document']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-102-u13-review') AND goal='conversation'), 14, 'npc', 'Fingers crossed, {{user_name}}!', 'うまくいきますように、{{user_name}}！', NULL, NULL, NULL);
