-- Vocab 103 - unit REVIEW capstones (standalone; only -review lessons).

-- Unit 1 review: The new flatmate
INSERT INTO vocab_lessons (slug, level_index, order_index, theme_id, title_en, title_ja, published, free) VALUES
  ('vocab-103-u1-review', 1, 90, (SELECT id FROM vocab_categories WHERE slug='getting-on-c1'), 'Review', '復習', TRUE, TRUE)
ON CONFLICT (slug) DO UPDATE SET level_index=EXCLUDED.level_index, order_index=EXCLUDED.order_index, theme_id=EXCLUDED.theme_id, title_en=EXCLUDED.title_en, title_ja=EXCLUDED.title_ja, published=EXCLUDED.published, free=EXCLUDED.free;
DELETE FROM vocab_lesson_items WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u1-review');
INSERT INTO vocab_lesson_items (lesson_id, sense_id, order_index)
SELECT (SELECT id FROM vocab_lessons WHERE slug='vocab-103-u1-review'), s.id, x.ord FROM (VALUES
  ('drift-apart.phrv.distance',0),('patch-up.phrv.mend',1),('hit-it-off.idiom.click',2),('warm-to.phrv.like',3),('take-to.phrv.like2',4),('fall-for.phrv.love',5),('grow-on.phrv.appeal',6),('look-down-on.phrv.despise',7),('come-across.phrv.seem',8),('stand-out.phrv.notable',9),('down-to-earth.adj.practical',10),('easygoing.adj.relaxed',11),('level-headed.adj.calm',12),('strong-willed.adj.determined',13),('self-conscious.adj.shy',14),('laid-back.adj.relaxed2',15)
) AS x(slug, ord) JOIN vocab_senses s ON s.slug = x.slug ON CONFLICT DO NOTHING;
DELETE FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u1-review');
INSERT INTO vocab_scenes (lesson_id, goal, order_index, title_en, title_ja, setting, npc_role) VALUES
  ((SELECT id FROM vocab_lessons WHERE slug='vocab-103-u1-review'), 'conversation', 0, 'The new flatmate', '新しいルームメイト', 'home', 'friend');
INSERT INTO vocab_scene_lines (scene_id, order_index, speaker, text_en, text_ja, blank_answer, blank_sense_id, options) VALUES
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u1-review') AND goal='conversation'), 0, 'npc', 'You met your new flatmate?', '新しいルームメイトに会った？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u1-review') AND goal='conversation'), 1, 'user', 'Yeah, we {hit it off} right away.', 'うん、すぐ意気投合した。', 'hit it off', (SELECT id FROM vocab_senses WHERE slug='hit-it-off.idiom.click'), ARRAY['hit it off','drift apart','look down on','patch up']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u1-review') AND goal='conversation'), 2, 'npc', 'Great. What''s she like?', 'いいね。どんな人？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u1-review') AND goal='conversation'), 3, 'user', 'Really {down-to-earth}; no drama at all.', 'すごく気取らない、面倒がない。', 'down-to-earth', (SELECT id FROM vocab_senses WHERE slug='down-to-earth.adj.practical'), ARRAY['down-to-earth','self-conscious','strong-willed','level-headed']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u1-review') AND goal='conversation'), 4, 'npc', 'Calm person?', '落ち着いてる？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u1-review') AND goal='conversation'), 5, 'user', 'Very {level-headed}; she handles stress well.', 'とても冷静、ストレスにも強い。', 'level-headed', (SELECT id FROM vocab_senses WHERE slug='level-headed.adj.calm'), ARRAY['level-headed','self-conscious','laid-back','easygoing']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u1-review') AND goal='conversation'), 6, 'npc', 'How does she seem to others?', '他の人にはどう見える？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u1-review') AND goal='conversation'), 7, 'user', 'She can {come across} as quiet, but she''s warm.', '静かな印象を与えるけど、温かい人。', 'come across', (SELECT id FROM vocab_senses WHERE slug='come-across.phrv.seem'), ARRAY['come across','stand out','warm to','grow on']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u1-review') AND goal='conversation'), 8, 'npc', 'Do you get along?', 'うまくやってる？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u1-review') AND goal='conversation'), 9, 'user', 'Mostly. We had one row but quickly did {patch up} things.', 'だいたい。一度もめたけど、すぐ修復した。', 'patch up', (SELECT id FROM vocab_senses WHERE slug='patch-up.phrv.mend'), ARRAY['patch up','drift apart','look down on','hit it off']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u1-review') AND goal='conversation'), 10, 'npc', 'Good. Does she fit in?', 'いいね。馴染んでる？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u1-review') AND goal='conversation'), 11, 'user', 'She really does {stand out} at parties.', 'パーティーでは本当に際立つ。', 'stand out', (SELECT id FROM vocab_senses WHERE slug='stand-out.phrv.notable'), ARRAY['stand out','come across','warm to','grow on']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u1-review') AND goal='conversation'), 12, 'npc', 'Sounds like a keeper.', 'いい人だね。', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u1-review') AND goal='conversation'), 13, 'user', 'Definitely. She''s really starting to {grow on} me.', '本当に。どんどん好きになってきてる。', 'grow on', (SELECT id FROM vocab_senses WHERE slug='grow-on.phrv.appeal'), ARRAY['grow on','drift apart','look down on','hit it off']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u1-review') AND goal='conversation'), 14, 'npc', 'Lucky you, {{user_name}}!', 'いいね、{{user_name}}！', NULL, NULL, NULL);

-- Unit 2 review: Reviewing a proposal
INSERT INTO vocab_lessons (slug, level_index, order_index, theme_id, title_en, title_ja, published, free) VALUES
  ('vocab-103-u2-review', 2, 90, (SELECT id FROM vocab_categories WHERE slug='making-a-point'), 'Review', '復習', TRUE, TRUE)
ON CONFLICT (slug) DO UPDATE SET level_index=EXCLUDED.level_index, order_index=EXCLUDED.order_index, theme_id=EXCLUDED.theme_id, title_en=EXCLUDED.title_en, title_ja=EXCLUDED.title_ja, published=EXCLUDED.published, free=EXCLUDED.free;
DELETE FROM vocab_lesson_items WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u2-review');
INSERT INTO vocab_lesson_items (lesson_id, sense_id, order_index)
SELECT (SELECT id FROM vocab_lessons WHERE slug='vocab-103-u2-review'), s.id, x.ord FROM (VALUES
  ('get-at.phrv.imply',0),('play-down.phrv.minimize',1),('touch-on.phrv.mention',2),('sum-up.phrv.summarize',3),('put-across.phrv.convey',4),('gloss-over.phrv.evade',5),('single-out.phrv.select',6),('harp-on.phrv.dwell',7),('bear-in-mind.idiom.remember',8),('take-into-account.idiom.consider',9),('see-eye-to-eye.idiom.agree',10),('beg-to-differ.idiom.disagree',11),('on-the-fence.idiom.undecided',12),('food-for-thought.idiom.reflect',13),('common-ground.idiom.shared',14),('devils-advocate.idiom.contrarian',15)
) AS x(slug, ord) JOIN vocab_senses s ON s.slug = x.slug ON CONFLICT DO NOTHING;
DELETE FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u2-review');
INSERT INTO vocab_scenes (lesson_id, goal, order_index, title_en, title_ja, setting, npc_role) VALUES
  ((SELECT id FROM vocab_lessons WHERE slug='vocab-103-u2-review'), 'conversation', 0, 'Reviewing a proposal', '提案を検討する', 'office', 'colleague');
INSERT INTO vocab_scene_lines (scene_id, order_index, speaker, text_en, text_ja, blank_answer, blank_sense_id, options) VALUES
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u2-review') AND goal='conversation'), 0, 'npc', 'Did you read my proposal?', '私の提案書読んだ？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u2-review') AND goal='conversation'), 1, 'user', 'Yes. Can you {sum up} the main goal for me?', 'うん。主な目的を要約してくれる？', 'sum up', (SELECT id FROM vocab_senses WHERE slug='sum-up.phrv.summarize'), ARRAY['sum up','harp on','single out','gloss over']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u2-review') AND goal='conversation'), 2, 'npc', 'Cut costs, keep quality.', 'コスト削減、品質維持。', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u2-review') AND goal='conversation'), 3, 'user', 'You {put across} that well in the intro.', '冒頭でそれをうまく伝えてたね。', 'put across', (SELECT id FROM vocab_senses WHERE slug='put-across.phrv.convey'), ARRAY['put across','gloss over','single out','harp on']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u2-review') AND goal='conversation'), 4, 'npc', 'Thanks. Any doubts?', 'ありがとう。疑問は？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u2-review') AND goal='conversation'), 5, 'user', 'I''m {on the fence} about the timeline.', 'スケジュールについては決めかねてる。', 'on the fence', (SELECT id FROM vocab_senses WHERE slug='on-the-fence.idiom.undecided'), ARRAY['on the fence','common ground','food for thought','devil''s advocate']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u2-review') AND goal='conversation'), 6, 'npc', 'Too tight?', 'きつすぎる？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u2-review') AND goal='conversation'), 7, 'user', 'Just {bear in mind} the holiday season.', '繁忙期を心に留めておいて。', 'bear in mind', (SELECT id FROM vocab_senses WHERE slug='bear-in-mind.idiom.remember'), ARRAY['bear in mind','see eye to eye','beg to differ','on the fence']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u2-review') AND goal='conversation'), 8, 'npc', 'Good catch. On the budget?', 'いい指摘。予算は？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u2-review') AND goal='conversation'), 9, 'user', 'There we {see eye to eye} completely.', 'そこは完全に意見一致。', 'see eye to eye', (SELECT id FROM vocab_senses WHERE slug='see-eye-to-eye.idiom.agree'), ARRAY['see eye to eye','beg to differ','bear in mind','take into account']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u2-review') AND goal='conversation'), 10, 'npc', 'Great, common vision helps.', 'いいね、共通のビジョンは助かる。', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u2-review') AND goal='conversation'), 11, 'user', 'Exactly, we have real {common ground}.', 'そう、本当に共通点がある。', 'common ground', (SELECT id FROM vocab_senses WHERE slug='common-ground.idiom.shared'), ARRAY['common ground','on the fence','food for thought','devil''s advocate']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u2-review') AND goal='conversation'), 12, 'npc', 'But don''t oversell it.', 'でも大げさにしないで。', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u2-review') AND goal='conversation'), 13, 'user', 'Agreed, I won''t {play down} the risks either.', '賛成、リスクも軽く扱わない。', 'play down', (SELECT id FROM vocab_senses WHERE slug='play-down.phrv.minimize'), ARRAY['play down','sum up','touch on','harp on']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u2-review') AND goal='conversation'), 14, 'npc', 'Nice work, {{user_name}}.', 'いい仕事、{{user_name}}。', NULL, NULL, NULL);

-- Unit 3 review: Kicking off a project
INSERT INTO vocab_lessons (slug, level_index, order_index, theme_id, title_en, title_ja, published, free) VALUES
  ('vocab-103-u3-review', 3, 90, (SELECT id FROM vocab_categories WHERE slug='getting-things-done-c1'), 'Review', '復習', TRUE, TRUE)
ON CONFLICT (slug) DO UPDATE SET level_index=EXCLUDED.level_index, order_index=EXCLUDED.order_index, theme_id=EXCLUDED.theme_id, title_en=EXCLUDED.title_en, title_ja=EXCLUDED.title_ja, published=EXCLUDED.published, free=EXCLUDED.free;
DELETE FROM vocab_lesson_items WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u3-review');
INSERT INTO vocab_lesson_items (lesson_id, sense_id, order_index)
SELECT (SELECT id FROM vocab_lessons WHERE slug='vocab-103-u3-review'), s.id, x.ord FROM (VALUES
  ('nail-down.phrv.finalize',0),('draw-up.phrv.prepare',1),('roll-out.phrv.launch',2),('follow-through.phrv.complete',3),('hammer-out.phrv.negotiate',4),('flesh-out.phrv.detail',5),('map-out.phrv.plan',6),('iron-out.phrv.resolve',7),('touch-base.idiom.contact',8),('on-the-same-page.idiom.aligned',9),('in-the-loop.idiom.informed',10),('pull-your-weight.idiom.contribute',11),('cut-corners.idiom.skimp',12),('step-up.phrv.rise',13),('take-the-lead.idiom.lead',14),('hit-the-ground-running.idiom.start',15)
) AS x(slug, ord) JOIN vocab_senses s ON s.slug = x.slug ON CONFLICT DO NOTHING;
DELETE FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u3-review');
INSERT INTO vocab_scenes (lesson_id, goal, order_index, title_en, title_ja, setting, npc_role) VALUES
  ((SELECT id FROM vocab_lessons WHERE slug='vocab-103-u3-review'), 'conversation', 0, 'Kicking off a project', 'プロジェクト始動', 'office', 'colleague');
INSERT INTO vocab_scene_lines (scene_id, order_index, speaker, text_en, text_ja, blank_answer, blank_sense_id, options) VALUES
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u3-review') AND goal='conversation'), 0, 'npc', 'Excited to lead the new project?', '新プロジェクトを率いるの、楽しみ？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u3-review') AND goal='conversation'), 1, 'user', 'Yes! First I''ll {nail down} the goals.', 'うん！まず目標を確定する。', 'nail down', (SELECT id FROM vocab_senses WHERE slug='nail-down.phrv.finalize'), ARRAY['nail down','roll out','follow through','hammer out']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u3-review') AND goal='conversation'), 2, 'npc', 'How will you keep everyone aligned?', 'どうやってみんなの足並みを揃える？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u3-review') AND goal='conversation'), 3, 'user', 'Weekly syncs to stay {on the same page}.', '毎週すり合わせて認識を合わせる。', 'on the same page', (SELECT id FROM vocab_senses WHERE slug='on-the-same-page.idiom.aligned'), ARRAY['on the same page','cut corners','touch base','in the loop']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u3-review') AND goal='conversation'), 4, 'npc', 'And quick check-ins?', '短い確認は？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u3-review') AND goal='conversation'), 5, 'user', 'Yes, I''ll {touch base} with each lead.', 'うん、各リーダーと連絡を取り合う。', 'touch base', (SELECT id FROM vocab_senses WHERE slug='touch-base.idiom.contact'), ARRAY['touch base','cut corners','step up','take the lead']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u3-review') AND goal='conversation'), 6, 'npc', 'What about slackers?', 'サボる人は？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u3-review') AND goal='conversation'), 7, 'user', 'I expect everyone to {pull your weight}.', '全員に役割を果たしてほしい。', 'pull your weight', (SELECT id FROM vocab_senses WHERE slug='pull-your-weight.idiom.contribute'), ARRAY['pull your weight','cut corners','touch base','step up']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u3-review') AND goal='conversation'), 8, 'npc', 'Any early problems?', '初期の問題は？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u3-review') AND goal='conversation'), 9, 'user', 'A few I''ll {iron out} this week.', 'いくつか今週解決する。', 'iron out', (SELECT id FROM vocab_senses WHERE slug='iron-out.phrv.resolve'), ARRAY['iron out','roll out','nail down','hammer out']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u3-review') AND goal='conversation'), 10, 'npc', 'When does it go live?', 'いつ公開？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u3-review') AND goal='conversation'), 11, 'user', 'We {roll out} to users next month.', '来月ユーザーに展開する。', 'roll out', (SELECT id FROM vocab_senses WHERE slug='roll-out.phrv.launch'), ARRAY['roll out','nail down','follow through','hammer out']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u3-review') AND goal='conversation'), 12, 'npc', 'Big responsibility.', '大きな責任だね。', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u3-review') AND goal='conversation'), 13, 'user', 'I''m ready to {step up}.', '一肌脱ぐ覚悟はできてる。', 'step up', (SELECT id FROM vocab_senses WHERE slug='step-up.phrv.rise'), ARRAY['step up','cut corners','touch base','take the lead']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u3-review') AND goal='conversation'), 14, 'npc', 'You''ll smash it, {{user_name}}.', '絶対うまくいくよ、{{user_name}}。', NULL, NULL, NULL);

-- Unit 4 review: Money talk
INSERT INTO vocab_lessons (slug, level_index, order_index, theme_id, title_en, title_ja, published, free) VALUES
  ('vocab-103-u4-review', 4, 90, (SELECT id FROM vocab_categories WHERE slug='spending-saving-c1'), 'Review', '復習', TRUE, TRUE)
ON CONFLICT (slug) DO UPDATE SET level_index=EXCLUDED.level_index, order_index=EXCLUDED.order_index, theme_id=EXCLUDED.theme_id, title_en=EXCLUDED.title_en, title_ja=EXCLUDED.title_ja, published=EXCLUDED.published, free=EXCLUDED.free;
DELETE FROM vocab_lesson_items WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u4-review');
INSERT INTO vocab_lesson_items (lesson_id, sense_id, order_index)
SELECT (SELECT id FROM vocab_lessons WHERE slug='vocab-103-u4-review'), s.id, x.ord FROM (VALUES
  ('splurge.v.spend',0),('scrape-by.phrv.survive',1),('rip-off.phrv.overcharge',2),('chip-in.phrv.contribute',3),('dip-into.phrv.usesavings',4),('fork-out.phrv.pay',5),('shell-out.phrv.pay2',6),('tighten-your-belt.idiom.economize',7),('weigh-up.phrv.assess',8),('bank-on.phrv.rely',9),('fall-through.phrv.fail',10),('make-ends-meet.idiom.manage',11),('break-even.idiom.balance',12),('in-the-red.idiom.debt',13),('nest-egg.idiom.savings',14),('live-within-means.idiom.budget',15)
) AS x(slug, ord) JOIN vocab_senses s ON s.slug = x.slug ON CONFLICT DO NOTHING;
DELETE FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u4-review');
INSERT INTO vocab_scenes (lesson_id, goal, order_index, title_en, title_ja, setting, npc_role) VALUES
  ((SELECT id FROM vocab_lessons WHERE slug='vocab-103-u4-review'), 'conversation', 0, 'Money talk', 'お金の話', 'cafe', 'friend');
INSERT INTO vocab_scene_lines (scene_id, order_index, speaker, text_en, text_ja, blank_answer, blank_sense_id, options) VALUES
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u4-review') AND goal='conversation'), 0, 'npc', 'Saving for anything big?', '何か大きなもののために貯金してる？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u4-review') AND goal='conversation'), 1, 'user', 'Building a {nest egg} for a house.', '家のために蓄えを作ってる。', 'nest egg', (SELECT id FROM vocab_senses WHERE slug='nest-egg.idiom.savings'), ARRAY['nest egg','break even','in the red','make ends meet']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u4-review') AND goal='conversation'), 2, 'npc', 'Nice. Easy to save?', 'いいね。貯めやすい？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u4-review') AND goal='conversation'), 3, 'user', 'It''s tight; I barely {make ends meet}.', '厳しい、ぎりぎり収支を合わせてる。', 'make ends meet', (SELECT id FROM vocab_senses WHERE slug='make-ends-meet.idiom.manage'), ARRAY['make ends meet','break even','in the red','nest egg']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u4-review') AND goal='conversation'), 4, 'npc', 'Cutting back then?', 'じゃあ節約中？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u4-review') AND goal='conversation'), 5, 'user', 'Yeah, I really {tighten your belt} these days.', 'うん、最近は本当に節約してる。', 'tighten your belt', (SELECT id FROM vocab_senses WHERE slug='tighten-your-belt.idiom.economize'), ARRAY['tighten your belt','splurge','chip in','rip off']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u4-review') AND goal='conversation'), 6, 'npc', 'No treats at all?', 'ご褒美は全然なし？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u4-review') AND goal='conversation'), 7, 'user', 'Once a month I {splurge} on something small.', '月に一度、小さく奮発する。', 'splurge', (SELECT id FROM vocab_senses WHERE slug='splurge.v.spend'), ARRAY['splurge','scrape by','chip in','dip into']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u4-review') AND goal='conversation'), 8, 'npc', 'Fair. We''re doing a group gift.', 'いいね。グループでプレゼントするんだ。', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u4-review') AND goal='conversation'), 9, 'user', 'I''ll {chip in}, count me in.', '出し合うよ、入れて。', 'chip in', (SELECT id FROM vocab_senses WHERE slug='chip-in.phrv.contribute'), ARRAY['chip in','splurge','scrape by','dip into']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u4-review') AND goal='conversation'), 10, 'npc', 'Thinking of investing too?', '投資も考えてる？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u4-review') AND goal='conversation'), 11, 'user', 'I still need to {weigh up} my options.', 'まだ選択肢をよく検討しないと。', 'weigh up', (SELECT id FROM vocab_senses WHERE slug='weigh-up.phrv.assess'), ARRAY['weigh up','bank on','fall through','break even']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u4-review') AND goal='conversation'), 12, 'npc', 'Don''t rush it.', '焦らないで。', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u4-review') AND goal='conversation'), 13, 'user', 'Right, and if a plan {fall through}, no stress.', 'うん、計画が流れても気にしない。', 'fall through', (SELECT id FROM vocab_senses WHERE slug='fall-through.phrv.fail'), ARRAY['fall through','weigh up','bank on','break even']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u4-review') AND goal='conversation'), 14, 'npc', 'Wise, {{user_name}}.', '賢いね、{{user_name}}。', NULL, NULL, NULL);

-- Unit 5 review: A hard week at work
INSERT INTO vocab_lessons (slug, level_index, order_index, theme_id, title_en, title_ja, published, free) VALUES
  ('vocab-103-u5-review', 5, 90, (SELECT id FROM vocab_categories WHERE slug='troubleshooting-c1'), 'Review', '復習', TRUE, TRUE)
ON CONFLICT (slug) DO UPDATE SET level_index=EXCLUDED.level_index, order_index=EXCLUDED.order_index, theme_id=EXCLUDED.theme_id, title_en=EXCLUDED.title_en, title_ja=EXCLUDED.title_ja, published=EXCLUDED.published, free=EXCLUDED.free;
DELETE FROM vocab_lesson_items WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u5-review');
INSERT INTO vocab_lesson_items (lesson_id, sense_id, order_index)
SELECT (SELECT id FROM vocab_lessons WHERE slug='vocab-103-u5-review'), s.id, x.ord FROM (VALUES
  ('work-around.phrv.bypass',0),('clear-up.phrv.resolve',1),('head-off.phrv.prevent',2),('stave-off.phrv.delay',3),('root-out.phrv.eliminate',4),('smooth-over.phrv.ease',5),('tide-over.phrv.help',6),('sort-through.phrv.sift',7),('the-last-straw.idiom.limit',8),('back-to-drawing-board.idiom.restart',9),('nip-in-the-bud.idiom.stopearly',10),('at-a-loss.idiom.puzzled',11),('in-a-bind.idiom.stuck',12),('spanner-in-works.idiom.disrupt',13),('buy-time.idiom.delay',14),('damage-control.idiom.limit2',15)
) AS x(slug, ord) JOIN vocab_senses s ON s.slug = x.slug ON CONFLICT DO NOTHING;
DELETE FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u5-review');
INSERT INTO vocab_scenes (lesson_id, goal, order_index, title_en, title_ja, setting, npc_role) VALUES
  ((SELECT id FROM vocab_lessons WHERE slug='vocab-103-u5-review'), 'conversation', 0, 'A hard week at work', '仕事で大変な一週間', 'cafe', 'friend');
INSERT INTO vocab_scene_lines (scene_id, order_index, speaker, text_en, text_ja, blank_answer, blank_sense_id, options) VALUES
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u5-review') AND goal='conversation'), 0, 'npc', 'Rough week at work?', '仕事、大変な週だった？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u5-review') AND goal='conversation'), 1, 'user', 'The server crash was {the last straw}.', 'サーバーダウンで限界だった。', 'the last straw', (SELECT id FROM vocab_senses WHERE slug='the-last-straw.idiom.limit'), ARRAY['the last straw','at a loss','in a bind','buy time']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u5-review') AND goal='conversation'), 2, 'npc', 'Yikes. Big impact?', 'うわ。影響大きい？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u5-review') AND goal='conversation'), 3, 'user', 'We spent the day doing {damage control}.', '一日中、事後対応してた。', 'damage control', (SELECT id FROM vocab_senses WHERE slug='damage-control.idiom.limit2'), ARRAY['damage control','at a loss','in a bind','buy time']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u5-review') AND goal='conversation'), 4, 'npc', 'Did you fix the cause?', '原因は直した？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u5-review') AND goal='conversation'), 5, 'user', 'IT helped {clear up} the main issue.', 'ITが主な問題を解決してくれた。', 'clear up', (SELECT id FROM vocab_senses WHERE slug='clear-up.phrv.resolve'), ARRAY['clear up','head off','stave off','root out']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u5-review') AND goal='conversation'), 6, 'npc', 'Any quick fix meanwhile?', 'その間の応急策は？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u5-review') AND goal='conversation'), 7, 'user', 'We found a way to {work around} it.', '回避する方法を見つけた。', 'work around', (SELECT id FROM vocab_senses WHERE slug='work-around.phrv.bypass'), ARRAY['work around','clear up','head off','stave off']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u5-review') AND goal='conversation'), 8, 'npc', 'Were you overwhelmed?', '参っちゃった？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u5-review') AND goal='conversation'), 9, 'user', 'At first I was {at a loss}, yeah.', '最初は途方に暮れてた。', 'at a loss', (SELECT id FROM vocab_senses WHERE slug='at-a-loss.idiom.puzzled'), ARRAY['at a loss','in a bind','buy time','nip in the bud']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u5-review') AND goal='conversation'), 10, 'npc', 'How did you cope?', 'どう乗り切った？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u5-review') AND goal='conversation'), 11, 'user', 'We paused releases to {buy time}.', 'リリースを止めて時間を稼いだ。', 'buy time', (SELECT id FROM vocab_senses WHERE slug='buy-time.idiom.delay'), ARRAY['buy time','at a loss','in a bind','nip in the bud']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u5-review') AND goal='conversation'), 12, 'npc', 'Preventing a repeat?', '再発は防げる？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u5-review') AND goal='conversation'), 13, 'user', 'Yes, new checks {head off} future crashes.', 'うん、新しいチェックが今後のダウンを未然に防ぐ。', 'head off', (SELECT id FROM vocab_senses WHERE slug='head-off.phrv.prevent'), ARRAY['head off','work around','sort through','smooth over']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u5-review') AND goal='conversation'), 14, 'npc', 'You handled it well, {{user_name}}.', 'うまく対処したね、{{user_name}}。', NULL, NULL, NULL);

-- Unit 6 review: Before a big day
INSERT INTO vocab_lessons (slug, level_index, order_index, theme_id, title_en, title_ja, published, free) VALUES
  ('vocab-103-u6-review', 6, 90, (SELECT id FROM vocab_categories WHERE slug='handling-feelings-c1'), 'Review', '復習', TRUE, TRUE)
ON CONFLICT (slug) DO UPDATE SET level_index=EXCLUDED.level_index, order_index=EXCLUDED.order_index, theme_id=EXCLUDED.theme_id, title_en=EXCLUDED.title_en, title_ja=EXCLUDED.title_ja, published=EXCLUDED.published, free=EXCLUDED.free;
DELETE FROM vocab_lesson_items WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u6-review');
INSERT INTO vocab_lesson_items (lesson_id, sense_id, order_index)
SELECT (SELECT id FROM vocab_lessons WHERE slug='vocab-103-u6-review'), s.id, x.ord FROM (VALUES
  ('well-up.phrv.tears',0),('choke-up.phrv.emotional',1),('simmer-down.phrv.calm',2),('lash-out.phrv.attack',3),('open-up.phrv.confide',4),('bottle-up.phrv.suppress',5),('snap-at.phrv.snap',6),('perk-up.phrv.cheer',7),('on-edge.idiom.tense',8),('over-the-moon.idiom.thrilled',9),('down-in-dumps.idiom.sad',10),('mixed-feelings.idiom.ambivalent',11),('at-ease.idiom.relaxed',12),('on-cloud-nine.idiom.euphoric',13),('lose-your-cool.idiom.angry',14),('get-cold-feet.idiom.nervous',15)
) AS x(slug, ord) JOIN vocab_senses s ON s.slug = x.slug ON CONFLICT DO NOTHING;
DELETE FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u6-review');
INSERT INTO vocab_scenes (lesson_id, goal, order_index, title_en, title_ja, setting, npc_role) VALUES
  ((SELECT id FROM vocab_lessons WHERE slug='vocab-103-u6-review'), 'conversation', 0, 'Before a big day', '大事な日の前に', 'home', 'friend');
INSERT INTO vocab_scene_lines (scene_id, order_index, speaker, text_en, text_ja, blank_answer, blank_sense_id, options) VALUES
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u6-review') AND goal='conversation'), 0, 'npc', 'Big presentation tomorrow, right?', '明日は大事なプレゼンだよね？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u6-review') AND goal='conversation'), 1, 'user', 'Yeah, I''m a bit {on edge} about it.', 'うん、ちょっとピリピリしてる。', 'on edge', (SELECT id FROM vocab_senses WHERE slug='on-edge.idiom.tense'), ARRAY['on edge','over the moon','at ease','down in the dumps']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u6-review') AND goal='conversation'), 2, 'npc', 'Nervous is normal.', '緊張は普通だよ。', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u6-review') AND goal='conversation'), 3, 'user', 'I just hope I don''t {get cold feet} on stage.', '舞台で怖じ気づかないといいけど。', 'get cold feet', (SELECT id FROM vocab_senses WHERE slug='get-cold-feet.idiom.nervous'), ARRAY['get cold feet','over the moon','at ease','mixed feelings']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u6-review') AND goal='conversation'), 4, 'npc', 'You''ve prepared well.', 'よく準備したよ。', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u6-review') AND goal='conversation'), 5, 'user', 'True. I''ll {simmer down} with some breathing.', '確かに。深呼吸で落ち着く。', 'simmer down', (SELECT id FROM vocab_senses WHERE slug='simmer-down.phrv.calm'), ARRAY['simmer down','lash out','perk up','open up']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u6-review') AND goal='conversation'), 6, 'npc', 'Talk it through with me.', '私に話してみて。', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u6-review') AND goal='conversation'), 7, 'user', 'Thanks, it helps to {open up} beforehand.', 'ありがとう、前もって話すと楽になる。', 'open up', (SELECT id FROM vocab_senses WHERE slug='open-up.phrv.confide'), ARRAY['open up','bottle up','snap at','perk up']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u6-review') AND goal='conversation'), 8, 'npc', 'You''ll smash it.', '絶対うまくいく。', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u6-review') AND goal='conversation'), 9, 'user', 'Your support makes me {perk up}.', '君の応援で元気が出る。', 'perk up', (SELECT id FROM vocab_senses WHERE slug='perk-up.phrv.cheer'), ARRAY['perk up','bottle up','snap at','well up']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u6-review') AND goal='conversation'), 10, 'npc', 'And after, we celebrate.', '終わったらお祝いね。', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u6-review') AND goal='conversation'), 11, 'user', 'If it goes well, I''ll be {over the moon}.', 'うまくいったら大喜びだ。', 'over the moon', (SELECT id FROM vocab_senses WHERE slug='over-the-moon.idiom.thrilled'), ARRAY['over the moon','down in the dumps','on edge','at ease']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u6-review') AND goal='conversation'), 12, 'npc', 'It will. Relax tonight.', '大丈夫。今夜はリラックスして。', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u6-review') AND goal='conversation'), 13, 'user', 'I feel more {at ease} already.', 'もう少し落ち着いてきた。', 'at ease', (SELECT id FROM vocab_senses WHERE slug='at-ease.idiom.relaxed'), ARRAY['at ease','over the moon','on edge','down in the dumps']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u6-review') AND goal='conversation'), 14, 'npc', 'Go get ''em, {{user_name}}!', 'やってやれ、{{user_name}}！', NULL, NULL, NULL);

-- Unit 7 review: After a meetup
INSERT INTO vocab_lessons (slug, level_index, order_index, theme_id, title_en, title_ja, published, free) VALUES
  ('vocab-103-u7-review', 7, 90, (SELECT id FROM vocab_categories WHERE slug='in-conversation-c1'), 'Review', '復習', TRUE, TRUE)
ON CONFLICT (slug) DO UPDATE SET level_index=EXCLUDED.level_index, order_index=EXCLUDED.order_index, theme_id=EXCLUDED.theme_id, title_en=EXCLUDED.title_en, title_ja=EXCLUDED.title_ja, published=EXCLUDED.published, free=EXCLUDED.free;
DELETE FROM vocab_lesson_items WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u7-review');
INSERT INTO vocab_lesson_items (lesson_id, sense_id, order_index)
SELECT (SELECT id FROM vocab_lessons WHERE slug='vocab-103-u7-review'), s.id, x.ord FROM (VALUES
  ('chime-in.phrv.join',0),('butt-in.phrv.interrupt',1),('talk-over.phrv.interrupt2',2),('drown-out.phrv.mask',3),('blurt-out.phrv.exclaim',4),('ramble-on.phrv.digress',5),('tune-out.phrv.ignore',6),('get-through-to.phrv.reach',7),('break-the-ice.idiom.relax',8),('small-talk.idiom.chat',9),('same-wavelength.idiom.attuned',10),('keep-in-touch.idiom.contact',11),('out-of-the-blue.idiom.sudden',12),('strike-up.phrv.begin',13),('read-between-lines.idiom.infer',14),('put-in-good-word.idiom.recommend',15)
) AS x(slug, ord) JOIN vocab_senses s ON s.slug = x.slug ON CONFLICT DO NOTHING;
DELETE FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u7-review');
INSERT INTO vocab_scenes (lesson_id, goal, order_index, title_en, title_ja, setting, npc_role) VALUES
  ((SELECT id FROM vocab_lessons WHERE slug='vocab-103-u7-review'), 'conversation', 0, 'After a meetup', '交流会のあと', 'cafe', 'friend');
INSERT INTO vocab_scene_lines (scene_id, order_index, speaker, text_en, text_ja, blank_answer, blank_sense_id, options) VALUES
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u7-review') AND goal='conversation'), 0, 'npc', 'How was the meetup?', '交流会どうだった？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u7-review') AND goal='conversation'), 1, 'user', 'Good! A quiz helped {break the ice}.', 'よかった！クイズで打ち解けた。', 'break the ice', (SELECT id FROM vocab_senses WHERE slug='break-the-ice.idiom.relax'), ARRAY['break the ice','small talk','keep in touch','out of the blue']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u7-review') AND goal='conversation'), 2, 'npc', 'Chatty crowd?', 'おしゃべりな人たち？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u7-review') AND goal='conversation'), 3, 'user', 'A bit; some people {talk over} each other.', '少し、かぶせて話す人もいた。', 'talk over', (SELECT id FROM vocab_senses WHERE slug='talk-over.phrv.interrupt2'), ARRAY['talk over','chime in','tune out','get through to']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u7-review') AND goal='conversation'), 4, 'npc', 'Did you speak up?', '発言した？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u7-review') AND goal='conversation'), 5, 'user', 'I''d {chime in} when I had a point.', '言いたいことがある時は口をはさんだ。', 'chime in', (SELECT id FROM vocab_senses WHERE slug='chime-in.phrv.join'), ARRAY['chime in','butt in','talk over','drown out']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u7-review') AND goal='conversation'), 6, 'npc', 'Any boring bits?', '退屈な場面は？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u7-review') AND goal='conversation'), 7, 'user', 'One long speech, I did {tune out}.', '長いスピーチで、聞き流しちゃった。', 'tune out', (SELECT id FROM vocab_senses WHERE slug='tune-out.phrv.ignore'), ARRAY['tune out','chime in','butt in','blurt out']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u7-review') AND goal='conversation'), 8, 'npc', 'Meet anyone good?', 'いい人に会った？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u7-review') AND goal='conversation'), 9, 'user', 'A writer, totally {on the same wavelength}.', 'ある作家と完全に波長が合った。', 'on the same wavelength', (SELECT id FROM vocab_senses WHERE slug='same-wavelength.idiom.attuned'), ARRAY['on the same wavelength','small talk','keep in touch','out of the blue']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u7-review') AND goal='conversation'), 10, 'npc', 'Staying in contact?', '連絡取り合う？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u7-review') AND goal='conversation'), 11, 'user', 'Yes, we''ll {keep in touch}.', 'うん、連絡を取り合う。', 'keep in touch', (SELECT id FROM vocab_senses WHERE slug='keep-in-touch.idiom.contact'), ARRAY['keep in touch','small talk','break the ice','out of the blue']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u7-review') AND goal='conversation'), 12, 'npc', 'Could you tell they liked your work?', '君の作品を気に入ったと分かった？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u7-review') AND goal='conversation'), 13, 'user', 'I could {read between the lines}, yeah.', '行間を読めた、うん。', 'read between the lines', (SELECT id FROM vocab_senses WHERE slug='read-between-lines.idiom.infer'), ARRAY['read between the lines','small talk','keep in touch','break the ice']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u7-review') AND goal='conversation'), 14, 'npc', 'Great networking, {{user_name}}.', 'いい人脈づくり、{{user_name}}。', NULL, NULL, NULL);

-- Unit 8 review: A year of growth
INSERT INTO vocab_lessons (slug, level_index, order_index, theme_id, title_en, title_ja, published, free) VALUES
  ('vocab-103-u8-review', 8, 90, (SELECT id FROM vocab_categories WHERE slug='achievement-c1'), 'Review', '復習', TRUE, TRUE)
ON CONFLICT (slug) DO UPDATE SET level_index=EXCLUDED.level_index, order_index=EXCLUDED.order_index, theme_id=EXCLUDED.theme_id, title_en=EXCLUDED.title_en, title_ja=EXCLUDED.title_ja, published=EXCLUDED.published, free=EXCLUDED.free;
DELETE FROM vocab_lesson_items WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u8-review');
INSERT INTO vocab_lesson_items (lesson_id, sense_id, order_index)
SELECT (SELECT id FROM vocab_lessons WHERE slug='vocab-103-u8-review'), s.id, x.ord FROM (VALUES
  ('pull-off.phrv.achieve',0),('live-up-to.phrv.meet',1),('carry-off.phrv.manage',2),('sail-through.phrv.pass',3),('bounce-back.phrv.recover',4),('press-on.phrv.persist',5),('forge-ahead.phrv.advance',6),('come-through.phrv.deliver',7),('against-the-odds.idiom.unlikely',8),('steep-learning-curve.idiom.hard',9),('in-the-long-run.idiom.eventually',10),('cut-it-close.idiom.narrow',11),('hang-in-there.idiom.persevere',12),('go-extra-mile.idiom.exceed',13),('throw-in-towel.idiom.quit',14),('pay-dividends.idiom.reward',15)
) AS x(slug, ord) JOIN vocab_senses s ON s.slug = x.slug ON CONFLICT DO NOTHING;
DELETE FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u8-review');
INSERT INTO vocab_scenes (lesson_id, goal, order_index, title_en, title_ja, setting, npc_role) VALUES
  ((SELECT id FROM vocab_lessons WHERE slug='vocab-103-u8-review'), 'conversation', 0, 'A year of growth', '成長の一年', 'cafe', 'friend');
INSERT INTO vocab_scene_lines (scene_id, order_index, speaker, text_en, text_ja, blank_answer, blank_sense_id, options) VALUES
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u8-review') AND goal='conversation'), 0, 'npc', 'You launched your business this year!', '今年、起業したね！', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u8-review') AND goal='conversation'), 1, 'user', 'I did! Hard to believe I did {pull off} it.', 'うん！やり遂げたなんて信じられない。', 'pull off', (SELECT id FROM vocab_senses WHERE slug='pull-off.phrv.achieve'), ARRAY['pull off','live up to','sail through','bounce back']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u8-review') AND goal='conversation'), 2, 'npc', 'Against so much doubt.', 'あれだけ疑われたのに。', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u8-review') AND goal='conversation'), 3, 'user', 'Yeah, it grew {against the odds}.', 'うん、逆境の中で成長した。', 'against the odds', (SELECT id FROM vocab_senses WHERE slug='against-the-odds.idiom.unlikely'), ARRAY['against the odds','in the long run','cut it close','go the extra mile']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u8-review') AND goal='conversation'), 4, 'npc', 'Any low points?', 'どん底はあった？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u8-review') AND goal='conversation'), 5, 'user', 'A bad month, but I did {bounce back}.', 'ひどい月もあったけど、立ち直った。', 'bounce back', (SELECT id FROM vocab_senses WHERE slug='bounce-back.phrv.recover'), ARRAY['bounce back','live up to','sail through','come through']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u8-review') AND goal='conversation'), 6, 'npc', 'What kept you going?', '何が支えになった？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u8-review') AND goal='conversation'), 7, 'user', 'Friends told me to {hang in there}.', '友達が踏ん張れと言ってくれた。', 'hang in there', (SELECT id FROM vocab_senses WHERE slug='hang-in-there.idiom.persevere'), ARRAY['hang in there','throw in the towel','cut it close','go the extra mile']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u8-review') AND goal='conversation'), 8, 'npc', 'Did it meet your dream?', '夢に応えた？', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u8-review') AND goal='conversation'), 9, 'user', 'It really did {live up to} my hopes.', '本当に期待に応えてくれた。', 'live up to', (SELECT id FROM vocab_senses WHERE slug='live-up-to.phrv.meet'), ARRAY['live up to','pull off','sail through','press on']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u8-review') AND goal='conversation'), 10, 'npc', 'Your effort shows.', '努力が表れてる。', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u8-review') AND goal='conversation'), 11, 'user', 'I always try to {go the extra mile}.', 'いつも一層の努力をしようとしてる。', 'go the extra mile', (SELECT id FROM vocab_senses WHERE slug='go-extra-mile.idiom.exceed'), ARRAY['go the extra mile','hang in there','cut it close','in the long run']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u8-review') AND goal='conversation'), 12, 'npc', 'It''ll reward you.', '報われるよ。', NULL, NULL, NULL),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u8-review') AND goal='conversation'), 13, 'user', 'I hope it continues to {pay dividends}.', 'これからも実を結ぶといいな。', 'pay dividends', (SELECT id FROM vocab_senses WHERE slug='pay-dividends.idiom.reward'), ARRAY['pay dividends','hang in there','cut it close','go the extra mile']),
  ((SELECT id FROM vocab_scenes WHERE lesson_id=(SELECT id FROM vocab_lessons WHERE slug='vocab-103-u8-review') AND goal='conversation'), 14, 'npc', 'You earned it, {{user_name}}.', '君の実力だよ、{{user_name}}。', NULL, NULL, NULL);
