import base from './base-words.json'
import { ENRICHMENT, COLLOCATIONS, SENSES, SOUND_GUIDES, isPublished, type Enrichment, type Collocation, type Sense, type SoundGuide, type SoundSide } from './enrichment'

/**
 * Public API for the pronunciation pages. Base data (word, JA meaning, phoneme
 * category, British audio) comes from the Say After Me library via
 * base-words.json; enrichment.ts layers on the SEO detail. A word is "published"
 * — rendered, listed, in the sitemap — only when it has an enrichment entry.
 */

export type BaseWord = {
  slug: string
  word: string
  ja: string
  phoneme: string   // category key e.g. 'r_l'
  symbol: string    // IPA symbol for the category e.g. '/r/ vs /l/'
  name: string      // category name e.g. 'R/L'
  audioPrefix: string
  audioIndex: number
  audioSrc?: string        // direct UK female URL override (course-audio words); wins over the indexed pron-audio scheme
  audioSrcUs?: string      // direct US female URL override; falls back to audioSrc
  audioSrcMale?: string    // direct UK male URL, once generated by scripts/gen-pron-male-audio.mjs
  audioSrcUsMale?: string  // direct US male URL, same
}

export type BaseCategory = { key: string; symbol: string; name: string; slugs: string[] }

export type PronWord = BaseWord & Enrichment & {
  audioFemale: string
  audioFemaleUs: string
  /** Undefined when no male recording of this word exists. The course
   *  recordings are female-only, so these are absent for course-sourced words
   *  rather than silently falling back to the female take. */
  audioMale?: string
  audioMaleUs?: string
  collocations: Collocation[]
  senses: Sense[]
}

const BASE_WORDS = base.words as BaseWord[]
const CATEGORIES = base.categories as BaseCategory[]
const BY_SLUG = new Map(BASE_WORDS.map((w) => [w.slug, w]))

function audioUrl(w: BaseWord, gender: 'male' | 'female', accent: 'uk' | 'us' = 'uk'): string {
  const nn = String(w.audioIndex).padStart(2, '0')
  const dir = accent === 'us' ? `us-${gender}` : gender
  return `/pron-audio/${dir}/${w.audioPrefix}/${w.audioPrefix}_${nn}.mp3`
}

function merge(w: BaseWord): PronWord {
  // Each voice resolves independently: an explicit override wins, otherwise the
  // indexed library recording is used when the word has one (audioIndex 0 means
  // it was added for the course and has no library position). That lets a single
  // bad take be replaced — a heteronym read with the wrong sense, say — without
  // pulling the word's other three voices off the library.
  const hasLibrary = w.audioIndex > 0
  const lib = (g: 'male' | 'female', a: 'uk' | 'us') => (hasLibrary ? audioUrl(w, g, a) : undefined)
  return {
    ...w, ...ENRICHMENT[w.slug],
    audioFemale: w.audioSrc ?? lib('female', 'uk') ?? '',
    audioFemaleUs: w.audioSrcUs ?? w.audioSrc ?? lib('female', 'us') ?? '',
    audioMale: w.audioSrcMale ?? lib('male', 'uk'),
    audioMaleUs: w.audioSrcUsMale ?? lib('male', 'us'),
    collocations: COLLOCATIONS[w.slug] ?? [], senses: SENSES[w.slug] ?? [],
  }
}

/** Every published word (has enrichment), in base order. */
export function getPublishedWords(): PronWord[] {
  return BASE_WORDS.filter((w) => isPublished(w.slug)).map(merge)
}

/** A single published word, or undefined (unpublished / unknown). */
export function getWord(slug: string): PronWord | undefined {
  const w = BY_SLUG.get(slug.toLowerCase())
  if (!w || !isPublished(w.slug)) return undefined
  return merge(w)
}

/** The minimal-pair partner, if published. */
export function getPair(word: PronWord): PronWord | undefined {
  return word.pair ? getWord(word.pair) : undefined
}

/** Published words in the same phoneme family (excludes self and the pair — the
 *  pair gets its own prominent block). Capped for a tidy link row. */
export function familyWords(word: PronWord, limit = 8): PronWord[] {
  return getPublishedWords()
    .filter((w) => w.phoneme === word.phoneme && w.slug !== word.slug && w.slug !== word.pair)
    .slice(0, limit)
}

/** Published words grouped by phoneme category, for the index page. Only
 *  categories with at least one published word appear. */
export function publishedByCategory(): { key: string; symbol: string; name: string; words: PronWord[] }[] {
  return CATEGORIES
    .map((c) => ({ key: c.key, symbol: c.symbol, name: c.name, words: getPublishedWords().filter((w) => w.phoneme === c.key) }))
    .filter((c) => c.words.length > 0)
}

// ── Sound-guide hub pages ───────────────────────────────────────────────────
export type SoundGuideWithWords = SoundGuide & { words: PronWord[] }

function categoryPublishedWords(key: string): PronWord[] {
  return getPublishedWords().filter((w) => w.phoneme === key)
}

/**
 * A guide's published words. Guides that declare `trainer.pairs` own their
 * membership explicitly — needed for contrasts that span lexical sets (walk is
 * THOUGHT, work is NURSE) and for words that appear in two guides with
 * different partners (bat contrasts with but, and with bet). Guides without an
 * explicit pair list fall back to their base category.
 */
function guideWords(g: SoundGuide): PronWord[] {
  const out: PronWord[] = []
  const seen = new Set<string>()
  const push = (w: PronWord | undefined) => {
    if (!w || seen.has(w.slug)) return
    seen.add(w.slug)
    out.push(w)
  }
  const declared = g.trainer.pairs
  if (declared) for (const slug of declared.flat()) push(getWord(slug))
  else for (const w of categoryPublishedWords(g.key)) push(w)
  // Unpaired members come last so the contrast pairs stay at the front.
  for (const slug of g.extraWords ?? []) push(getWord(slug))
  return out
}

/** A sound guide by URL slug, with its published words — or undefined. */
export function getSoundGuide(slug: string): SoundGuideWithWords | undefined {
  const g = SOUND_GUIDES.find((x) => x.slug === slug)
  if (!g) return undefined
  const words = guideWords(g)
  return words.length ? { ...g, words } : undefined
}

/** Every sound guide that has published words. */
export function publishedSoundGuides(): SoundGuideWithWords[] {
  return SOUND_GUIDES.map((g) => ({ ...g, words: guideWords(g) })).filter((g) => g.words.length > 0)
}

/** The sound guide a word belongs to (for the word → hub link), if published.
 *  A word can sit in several guides; the first match wins as its primary home. */
export function soundGuideForWord(w: PronWord): SoundGuide | undefined {
  return SOUND_GUIDES.find((g) => guideWords(g).some((x) => x.slug === w.slug))
}

/** Minimal pairs within a category's published words (each pair once). */
export function minimalPairs(words: PronWord[]): [PronWord, PronWord][] {
  const bySlug = new Map(words.map((w) => [w.slug, w]))
  const seen = new Set<string>()
  const pairs: [PronWord, PronWord][] = []
  for (const w of words) {
    if (!w.pair || seen.has(w.slug)) continue
    const partner = bySlug.get(w.pair)
    if (partner) { pairs.push([w, partner]); seen.add(w.slug); seen.add(partner.slug) }
  }
  return pairs
}

// ── Interactive trainer props (for the SoundTrainer client component) ────────
/** `audio` holds the selectable takes, in the same order as `voiceLabels`. */
export type TWord = { slug: string; word: string; ipa: string; ja: string; role: 'r' | 'l'; audio: string[] }
export type SoundTrainerData = {
  slug: string
  titleJa: string
  sides: { r: SoundSide; l: SoundSide }
  featured: [TWord, TWord]
  pairs: [TWord, TWord][]
  faqs: { q: string; a: string }[]
  voiceLabels: string[]
}

/** Serialisable trainer data for a sound guide: the featured pair, all minimal
 *  pairs (each normalised to [r-side, l-side]), the two how-to sides, and FAQs.
 *  Every word carries its real UK male/female audio URLs. */
export function getSoundTrainer(slug: string): SoundTrainerData | undefined {
  const g = SOUND_GUIDES.find((x) => x.slug === slug)
  if (!g) return undefined
  const words = guideWords(g)
  if (!words.length) return undefined
  const bySlug = new Map(words.map((w) => [w.slug, w]))
  const roleOf = (s: string): 'r' | 'l' => (g.trainer.rSlugs.includes(s) ? 'r' : 'l')
  // A voice is offered only when every word in the guide has that recording, so
  // the labels and each word's `audio` array always line up — a word missing one
  // take drops that voice for the guide rather than shifting the others.
  const TAKES: [string, (w: PronWord) => string | undefined][] = [
    ['UK 女性', (w) => w.audioFemale],
    ['UK 男性', (w) => w.audioMale],
    ['US 女性', (w) => w.audioFemaleUs],
    ['US 男性', (w) => w.audioMaleUs],
  ]
  const available = TAKES.filter(([, get]) => words.every((w) => Boolean(get(w))))
  const voiceLabels = available.map(([label]) => label)
  const tw = (w: PronWord): TWord => ({
    slug: w.slug, word: w.word, ipa: w.ipa, ja: w.ja, role: roleOf(w.slug),
    audio: available.map(([, get]) => get(w) as string),
  })
  const fr = bySlug.get(g.trainer.featured[0])
  const fl = bySlug.get(g.trainer.featured[1])
  if (!fr || !fl) return undefined
  // Declared pairs win; otherwise derive them from each word's `pair` field.
  const rawPairs: [PronWord, PronWord][] = g.trainer.pairs
    ? g.trainer.pairs
        .map(([a, b]) => [bySlug.get(a), bySlug.get(b)] as const)
        .filter((p): p is readonly [PronWord, PronWord] => Boolean(p[0] && p[1]))
        .map(([a, b]) => [a, b] as [PronWord, PronWord])
    : minimalPairs(words)
  const pairs = rawPairs.map(([a, b]) => {
    const A = tw(a), B = tw(b)
    return (A.role === 'r' ? [A, B] : [B, A]) as [TWord, TWord]
  })
  return { slug: g.slug, titleJa: g.titleJa, sides: g.trainer.sides, featured: [tw(fr), tw(fl)], pairs, faqs: g.faqs, voiceLabels }
}
